//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeFactory.WinVs.Factory {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FactoryMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FactoryMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CodeFactory.WinVs.Factory.FactoryMessages", typeof(FactoryMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create &apos;{0}&apos;, cannot complete &apos;{1}&apos;.
        /// </summary>
        public static string CreationFailed {
            get {
                return ResourceManager.GetString("CreationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter &apos;{0}&apos; was not provided, cannot complete &apos;{1}&apos;..
        /// </summary>
        public static string InvalidParameter {
            get {
                return ResourceManager.GetString("InvalidParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load/return &apos;{0}&apos;, cannot complete &apos;{1}&apos;..
        /// </summary>
        public static string InvalidResult {
            get {
                return ResourceManager.GetString("InvalidResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load class &apos;{0}&apos;, cannot complete &apos;{1}&apos;.
        /// </summary>
        public static string LoadClassFailed {
            get {
                return ResourceManager.GetString("LoadClassFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not load the project folder configuration for the factory request &apos;{0}&apos;, cannot complete &apos;{1}&apos;.
        /// </summary>
        public static string LoadFolderConfigurationFailed {
            get {
                return ResourceManager.GetString("LoadFolderConfigurationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load interface &apos;{0}&apos;, cannot complete &apos;{1}&apos;.
        /// </summary>
        public static string LoadInterfaceFailed {
            get {
                return ResourceManager.GetString("LoadInterfaceFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not load the parameter configuration for the factory request &apos;{0}&apos;, cannot complete &apos;{1}&apos;.
        /// </summary>
        public static string LoadParameterConfigurationFailed {
            get {
                return ResourceManager.GetString("LoadParameterConfigurationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not load the project configuration for the factory request &apos;{0}&apos;, cannot complete &apos;{1}&apos;.
        /// </summary>
        public static string LoadProgramConfigurationFailed {
            get {
                return ResourceManager.GetString("LoadProgramConfigurationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Code Factory Automation was not provided, cannot complete &apos;{0}&apos;..
        /// </summary>
        public static string NoAutomationService {
            get {
                return ResourceManager.GetString("NoAutomationService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not load the required bool parameter &apos;{0}&apos; for the factory request &apos;{1}&apos;, cannot complete &apos;{2}&apos;.
        /// </summary>
        public static string RequiredBoolParameterNotFound {
            get {
                return ResourceManager.GetString("RequiredBoolParameterNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not load the required date parameter &apos;{0}&apos; for the factory request &apos;{1}&apos;, cannot complete &apos;{2}&apos;.
        /// </summary>
        public static string RequiredDateParameterNotFound {
            get {
                return ResourceManager.GetString("RequiredDateParameterNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not load the required project folder from the folder configuration &apos;{0}&apos; for the factory request &apos;{1}&apos;, cannot complete &apos;{2}&apos;.
        /// </summary>
        public static string RequiredFolderConfigNotFound {
            get {
                return ResourceManager.GetString("RequiredFolderConfigNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not load the required list parameter &apos;{0}&apos; for the factory request &apos;{1}&apos;, cannot complete &apos;{2}&apos;.
        /// </summary>
        public static string RequiredListParameterNotFound {
            get {
                return ResourceManager.GetString("RequiredListParameterNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not load the required project  from the project configuration &apos;{0}&apos; for the factory request &apos;{1}&apos;, cannot complete &apos;{2}&apos;.
        /// </summary>
        public static string RequiredProjectConfigNotFound {
            get {
                return ResourceManager.GetString("RequiredProjectConfigNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not load the required selected value parameter &apos;{0}&apos; for the factory request &apos;{1}&apos;, cannot complete &apos;{2}&apos;.
        /// </summary>
        public static string RequiredSelectedValueParameterNotFound {
            get {
                return ResourceManager.GetString("RequiredSelectedValueParameterNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not load the required string parameter &apos;{0}&apos; for the factory request &apos;{1}&apos;, cannot complete &apos;{2}&apos;.
        /// </summary>
        public static string RequiredStringParameterNotFound {
            get {
                return ResourceManager.GetString("RequiredStringParameterNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update &apos;{0}&apos;, cannot complete &apos;{1}&apos;.
        /// </summary>
        public static string UpdateFailed {
            get {
                return ResourceManager.GetString("UpdateFailed", resourceCulture);
            }
        }
    }
}
