### YamlMime:ManagedReference
items:
- uid: CodeFactory.WinVs.Loader.IVsPackageFileConfig
  commentId: T:CodeFactory.WinVs.Loader.IVsPackageFileConfig
  id: IVsPackageFileConfig
  parent: CodeFactory.WinVs.Loader
  children:
  - CodeFactory.WinVs.Loader.IVsPackageFileConfig.AssemblyPackagePath
  - CodeFactory.WinVs.Loader.IVsPackageFileConfig.AssemblyPhysicalPath
  - CodeFactory.WinVs.Loader.IVsPackageFileConfig.HasDebugDatabaseFile
  - CodeFactory.WinVs.Loader.IVsPackageFileConfig.PDBPackagePath
  - CodeFactory.WinVs.Loader.IVsPackageFileConfig.PDBPhysicalPath
  langs:
  - csharp
  - vb
  name: IVsPackageFileConfig
  nameWithType: IVsPackageFileConfig
  fullName: CodeFactory.WinVs.Loader.IVsPackageFileConfig
  type: Interface
  source:
    href: https://github.com/CodeFactoryLLC/CodeFactoryForWindows/blob/e63c05962945f61f2329e19d324f24a768806f18/Src/CodeFactoryForWindows/CodeFactory.WinVs/Loader/IVsPackageFileConfig.cs
  assemblies:
  - CodeFactory.WinVs
  namespace: CodeFactory.WinVs.Loader
  summary: Model definition that tracks information about where files are located and where to place them in the package definition.
  example: []
  syntax:
    content: public interface IVsPackageFileConfig
    content.vb: Public Interface IVsPackageFileConfig
- uid: CodeFactory.WinVs.Loader.IVsPackageFileConfig.HasDebugDatabaseFile
  commentId: P:CodeFactory.WinVs.Loader.IVsPackageFileConfig.HasDebugDatabaseFile
  id: HasDebugDatabaseFile
  parent: CodeFactory.WinVs.Loader.IVsPackageFileConfig
  langs:
  - csharp
  - vb
  name: HasDebugDatabaseFile
  nameWithType: IVsPackageFileConfig.HasDebugDatabaseFile
  fullName: CodeFactory.WinVs.Loader.IVsPackageFileConfig.HasDebugDatabaseFile
  type: Property
  source:
    href: https://github.com/CodeFactoryLLC/CodeFactoryForWindows/blob/e63c05962945f61f2329e19d324f24a768806f18/Src/CodeFactoryForWindows/CodeFactory.WinVs/Loader/IVsPackageFileConfig.cs
  assemblies:
  - CodeFactory.WinVs
  namespace: CodeFactory.WinVs.Loader
  summary: Flag that determines if the package library has a debug database file.
  example: []
  syntax:
    content: bool HasDebugDatabaseFile { get; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: ReadOnly Property HasDebugDatabaseFile As Boolean
  overload: CodeFactory.WinVs.Loader.IVsPackageFileConfig.HasDebugDatabaseFile*
- uid: CodeFactory.WinVs.Loader.IVsPackageFileConfig.AssemblyPhysicalPath
  commentId: P:CodeFactory.WinVs.Loader.IVsPackageFileConfig.AssemblyPhysicalPath
  id: AssemblyPhysicalPath
  parent: CodeFactory.WinVs.Loader.IVsPackageFileConfig
  langs:
  - csharp
  - vb
  name: AssemblyPhysicalPath
  nameWithType: IVsPackageFileConfig.AssemblyPhysicalPath
  fullName: CodeFactory.WinVs.Loader.IVsPackageFileConfig.AssemblyPhysicalPath
  type: Property
  source:
    href: https://github.com/CodeFactoryLLC/CodeFactoryForWindows/blob/e63c05962945f61f2329e19d324f24a768806f18/Src/CodeFactoryForWindows/CodeFactory.WinVs/Loader/IVsPackageFileConfig.cs
  assemblies:
  - CodeFactory.WinVs
  namespace: CodeFactory.WinVs.Loader
  summary: Physical location of the assembly to add to the package.
  example: []
  syntax:
    content: string AssemblyPhysicalPath { get; }
    parameters: []
    return:
      type: System.String
    content.vb: ReadOnly Property AssemblyPhysicalPath As String
  overload: CodeFactory.WinVs.Loader.IVsPackageFileConfig.AssemblyPhysicalPath*
- uid: CodeFactory.WinVs.Loader.IVsPackageFileConfig.AssemblyPackagePath
  commentId: P:CodeFactory.WinVs.Loader.IVsPackageFileConfig.AssemblyPackagePath
  id: AssemblyPackagePath
  parent: CodeFactory.WinVs.Loader.IVsPackageFileConfig
  langs:
  - csharp
  - vb
  name: AssemblyPackagePath
  nameWithType: IVsPackageFileConfig.AssemblyPackagePath
  fullName: CodeFactory.WinVs.Loader.IVsPackageFileConfig.AssemblyPackagePath
  type: Property
  source:
    href: https://github.com/CodeFactoryLLC/CodeFactoryForWindows/blob/e63c05962945f61f2329e19d324f24a768806f18/Src/CodeFactoryForWindows/CodeFactory.WinVs/Loader/IVsPackageFileConfig.cs
  assemblies:
  - CodeFactory.WinVs
  namespace: CodeFactory.WinVs.Loader
  summary: The logical location in the package the assembly will be stored.
  example: []
  syntax:
    content: string AssemblyPackagePath { get; }
    parameters: []
    return:
      type: System.String
    content.vb: ReadOnly Property AssemblyPackagePath As String
  overload: CodeFactory.WinVs.Loader.IVsPackageFileConfig.AssemblyPackagePath*
- uid: CodeFactory.WinVs.Loader.IVsPackageFileConfig.PDBPhysicalPath
  commentId: P:CodeFactory.WinVs.Loader.IVsPackageFileConfig.PDBPhysicalPath
  id: PDBPhysicalPath
  parent: CodeFactory.WinVs.Loader.IVsPackageFileConfig
  langs:
  - csharp
  - vb
  name: PDBPhysicalPath
  nameWithType: IVsPackageFileConfig.PDBPhysicalPath
  fullName: CodeFactory.WinVs.Loader.IVsPackageFileConfig.PDBPhysicalPath
  type: Property
  source:
    href: https://github.com/CodeFactoryLLC/CodeFactoryForWindows/blob/e63c05962945f61f2329e19d324f24a768806f18/Src/CodeFactoryForWindows/CodeFactory.WinVs/Loader/IVsPackageFileConfig.cs
  assemblies:
  - CodeFactory.WinVs
  namespace: CodeFactory.WinVs.Loader
  summary: Physical location of the PDB to add to the package.
  example: []
  syntax:
    content: string PDBPhysicalPath { get; }
    parameters: []
    return:
      type: System.String
    content.vb: ReadOnly Property PDBPhysicalPath As String
  overload: CodeFactory.WinVs.Loader.IVsPackageFileConfig.PDBPhysicalPath*
- uid: CodeFactory.WinVs.Loader.IVsPackageFileConfig.PDBPackagePath
  commentId: P:CodeFactory.WinVs.Loader.IVsPackageFileConfig.PDBPackagePath
  id: PDBPackagePath
  parent: CodeFactory.WinVs.Loader.IVsPackageFileConfig
  langs:
  - csharp
  - vb
  name: PDBPackagePath
  nameWithType: IVsPackageFileConfig.PDBPackagePath
  fullName: CodeFactory.WinVs.Loader.IVsPackageFileConfig.PDBPackagePath
  type: Property
  source:
    href: https://github.com/CodeFactoryLLC/CodeFactoryForWindows/blob/e63c05962945f61f2329e19d324f24a768806f18/Src/CodeFactoryForWindows/CodeFactory.WinVs/Loader/IVsPackageFileConfig.cs
  assemblies:
  - CodeFactory.WinVs
  namespace: CodeFactory.WinVs.Loader
  summary: The logical location in the package the PDB will be stored.
  example: []
  syntax:
    content: string PDBPackagePath { get; }
    parameters: []
    return:
      type: System.String
    content.vb: ReadOnly Property PDBPackagePath As String
  overload: CodeFactory.WinVs.Loader.IVsPackageFileConfig.PDBPackagePath*
references:
- uid: CodeFactory.WinVs.Loader
  commentId: N:CodeFactory.WinVs.Loader
  isExternal: true
  href: CodeFactory.html
  name: CodeFactory.WinVs.Loader
  nameWithType: CodeFactory.WinVs.Loader
  fullName: CodeFactory.WinVs.Loader
  spec.csharp:
  - uid: CodeFactory
    name: CodeFactory
    isExternal: true
    href: CodeFactory.html
  - name: .
  - uid: CodeFactory.WinVs
    name: WinVs
    isExternal: true
    href: CodeFactory.WinVs.html
  - name: .
  - uid: CodeFactory.WinVs.Loader
    name: Loader
    isExternal: true
    href: CodeFactory.WinVs.Loader.html
  spec.vb:
  - uid: CodeFactory
    name: CodeFactory
    isExternal: true
    href: CodeFactory.html
  - name: .
  - uid: CodeFactory.WinVs
    name: WinVs
    isExternal: true
    href: CodeFactory.WinVs.html
  - name: .
  - uid: CodeFactory.WinVs.Loader
    name: Loader
    isExternal: true
    href: CodeFactory.WinVs.Loader.html
- uid: CodeFactory.WinVs.Loader.IVsPackageFileConfig.HasDebugDatabaseFile*
  commentId: Overload:CodeFactory.WinVs.Loader.IVsPackageFileConfig.HasDebugDatabaseFile
  isExternal: true
  href: CodeFactory.WinVs.Loader.IVsPackageFileConfig.html#CodeFactory_WinVs_Loader_IVsPackageFileConfig_HasDebugDatabaseFile
  name: HasDebugDatabaseFile
  nameWithType: IVsPackageFileConfig.HasDebugDatabaseFile
  fullName: CodeFactory.WinVs.Loader.IVsPackageFileConfig.HasDebugDatabaseFile
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.boolean
  name: bool
  nameWithType: bool
  fullName: bool
  nameWithType.vb: Boolean
  fullName.vb: Boolean
  name.vb: Boolean
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: CodeFactory.WinVs.Loader.IVsPackageFileConfig.AssemblyPhysicalPath*
  commentId: Overload:CodeFactory.WinVs.Loader.IVsPackageFileConfig.AssemblyPhysicalPath
  isExternal: true
  href: CodeFactory.WinVs.Loader.IVsPackageFileConfig.html#CodeFactory_WinVs_Loader_IVsPackageFileConfig_AssemblyPhysicalPath
  name: AssemblyPhysicalPath
  nameWithType: IVsPackageFileConfig.AssemblyPhysicalPath
  fullName: CodeFactory.WinVs.Loader.IVsPackageFileConfig.AssemblyPhysicalPath
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: CodeFactory.WinVs.Loader.IVsPackageFileConfig.AssemblyPackagePath*
  commentId: Overload:CodeFactory.WinVs.Loader.IVsPackageFileConfig.AssemblyPackagePath
  isExternal: true
  href: CodeFactory.WinVs.Loader.IVsPackageFileConfig.html#CodeFactory_WinVs_Loader_IVsPackageFileConfig_AssemblyPackagePath
  name: AssemblyPackagePath
  nameWithType: IVsPackageFileConfig.AssemblyPackagePath
  fullName: CodeFactory.WinVs.Loader.IVsPackageFileConfig.AssemblyPackagePath
- uid: CodeFactory.WinVs.Loader.IVsPackageFileConfig.PDBPhysicalPath*
  commentId: Overload:CodeFactory.WinVs.Loader.IVsPackageFileConfig.PDBPhysicalPath
  isExternal: true
  href: CodeFactory.WinVs.Loader.IVsPackageFileConfig.html#CodeFactory_WinVs_Loader_IVsPackageFileConfig_PDBPhysicalPath
  name: PDBPhysicalPath
  nameWithType: IVsPackageFileConfig.PDBPhysicalPath
  fullName: CodeFactory.WinVs.Loader.IVsPackageFileConfig.PDBPhysicalPath
- uid: CodeFactory.WinVs.Loader.IVsPackageFileConfig.PDBPackagePath*
  commentId: Overload:CodeFactory.WinVs.Loader.IVsPackageFileConfig.PDBPackagePath
  isExternal: true
  href: CodeFactory.WinVs.Loader.IVsPackageFileConfig.html#CodeFactory_WinVs_Loader_IVsPackageFileConfig_PDBPackagePath
  name: PDBPackagePath
  nameWithType: IVsPackageFileConfig.PDBPackagePath
  fullName: CodeFactory.WinVs.Loader.IVsPackageFileConfig.PDBPackagePath
