### YamlMime:ManagedReference
items:
- uid: CodeFactory.WinVs.Commands.IVsConfigurableCommand`1
  commentId: T:CodeFactory.WinVs.Commands.IVsConfigurableCommand`1
  id: IVsConfigurableCommand`1
  parent: CodeFactory.WinVs.Commands
  children:
  - CodeFactory.WinVs.Commands.IVsConfigurableCommand`1.LoadExternalConfigDefinition
  langs:
  - csharp
  - vb
  name: IVsConfigurableCommand<TModel>
  nameWithType: IVsConfigurableCommand<TModel>
  fullName: CodeFactory.WinVs.Commands.IVsConfigurableCommand<TModel>
  type: Interface
  source:
    href: https://github.com/CodeFactoryLLC/CodeFactoryForWindows/blob/19e816ffdf1ba504be6987736bbac42e2d241405/Src/CodeFactoryForWindows/CodeFactory.WinVs/Commands/IVsConfigurableCommand.cs
  assemblies:
  - CodeFactory.WinVs
  namespace: CodeFactory.WinVs.Commands
  syntax:
    content: 'public interface IVsConfigurableCommand<TModel> : IVsFactoryCommand<TModel>, IVsCommandInformation, ICommand<TModel>, ICommandBase<TModel> where TModel : class'
    typeParameters:
    - id: TModel
    content.vb: Public Interface IVsConfigurableCommand(Of TModel As Class) Inherits IVsFactoryCommand(Of TModel), IVsCommandInformation, ICommand(Of TModel), ICommandBase(Of TModel)
  inheritedMembers:
  - CodeFactory.WinVs.Commands.IVsFactoryCommand{{TModel}}.VisualStudioActions
  - CodeFactory.WinVs.Commands.IVsCommandInformation.CommandTitle
  - CodeFactory.WinVs.Commands.IVsCommandInformation.CommandDescription
  - CodeFactory.WinVs.Commands.IVsCommandInformation.CommandType
  - CodeFactory.ICommand{{TModel}}.EnableCommandAsync({TModel})
  - CodeFactory.ICommandBase{{TModel}}.ExecuteCommandAsync({TModel})
  nameWithType.vb: IVsConfigurableCommand(Of TModel)
  fullName.vb: CodeFactory.WinVs.Commands.IVsConfigurableCommand(Of TModel)
  name.vb: IVsConfigurableCommand(Of TModel)
- uid: CodeFactory.WinVs.Commands.IVsConfigurableCommand`1.LoadExternalConfigDefinition
  commentId: M:CodeFactory.WinVs.Commands.IVsConfigurableCommand`1.LoadExternalConfigDefinition
  id: LoadExternalConfigDefinition
  parent: CodeFactory.WinVs.Commands.IVsConfigurableCommand`1
  langs:
  - csharp
  - vb
  name: LoadExternalConfigDefinition()
  nameWithType: IVsConfigurableCommand<TModel>.LoadExternalConfigDefinition()
  fullName: CodeFactory.WinVs.Commands.IVsConfigurableCommand<TModel>.LoadExternalConfigDefinition()
  type: Method
  source:
    href: https://github.com/CodeFactoryLLC/CodeFactoryForWindows/blob/19e816ffdf1ba504be6987736bbac42e2d241405/Src/CodeFactoryForWindows/CodeFactory.WinVs/Commands/IVsConfigurableCommand.cs
  assemblies:
  - CodeFactory.WinVs
  namespace: CodeFactory.WinVs.Commands
  summary: Loads the external configuration definition for this command.
  example: []
  syntax:
    content: ConfigCommand LoadExternalConfigDefinition()
    return:
      type: CodeFactory.WinVs.Commands.ConfigCommand
      description: Will return the command configuration or null if this command does not support external configurations.
    content.vb: Function LoadExternalConfigDefinition() As ConfigCommand
  overload: CodeFactory.WinVs.Commands.IVsConfigurableCommand`1.LoadExternalConfigDefinition*
  nameWithType.vb: IVsConfigurableCommand(Of TModel).LoadExternalConfigDefinition()
  fullName.vb: CodeFactory.WinVs.Commands.IVsConfigurableCommand(Of TModel).LoadExternalConfigDefinition()
references:
- uid: CodeFactory.WinVs.Commands
  commentId: N:CodeFactory.WinVs.Commands
  isExternal: true
  href: CodeFactory.html
  name: CodeFactory.WinVs.Commands
  nameWithType: CodeFactory.WinVs.Commands
  fullName: CodeFactory.WinVs.Commands
  spec.csharp:
  - uid: CodeFactory
    name: CodeFactory
    isExternal: true
    href: CodeFactory.html
  - name: .
  - uid: CodeFactory.WinVs
    name: WinVs
    isExternal: true
    href: CodeFactory.WinVs.html
  - name: .
  - uid: CodeFactory.WinVs.Commands
    name: Commands
    isExternal: true
    href: CodeFactory.WinVs.Commands.html
  spec.vb:
  - uid: CodeFactory
    name: CodeFactory
    isExternal: true
    href: CodeFactory.html
  - name: .
  - uid: CodeFactory.WinVs
    name: WinVs
    isExternal: true
    href: CodeFactory.WinVs.html
  - name: .
  - uid: CodeFactory.WinVs.Commands
    name: Commands
    isExternal: true
    href: CodeFactory.WinVs.Commands.html
- uid: CodeFactory.WinVs.Commands.IVsFactoryCommand{{TModel}}.VisualStudioActions
  commentId: P:CodeFactory.WinVs.Commands.IVsFactoryCommand{`0}.VisualStudioActions
  parent: CodeFactory.WinVs.Commands.IVsFactoryCommand{{TModel}}
  definition: CodeFactory.WinVs.Commands.IVsFactoryCommand`1.VisualStudioActions
  href: CodeFactory.WinVs.Commands.IVsFactoryCommand-1.html#CodeFactory_WinVs_Commands_IVsFactoryCommand_1_VisualStudioActions
  name: VisualStudioActions
  nameWithType: IVsFactoryCommand<TModel>.VisualStudioActions
  fullName: CodeFactory.WinVs.Commands.IVsFactoryCommand<TModel>.VisualStudioActions
  nameWithType.vb: IVsFactoryCommand(Of TModel).VisualStudioActions
  fullName.vb: CodeFactory.WinVs.Commands.IVsFactoryCommand(Of TModel).VisualStudioActions
- uid: CodeFactory.WinVs.Commands.IVsCommandInformation.CommandTitle
  commentId: P:CodeFactory.WinVs.Commands.IVsCommandInformation.CommandTitle
  parent: CodeFactory.WinVs.Commands.IVsCommandInformation
  isExternal: true
  href: CodeFactory.WinVs.Commands.IVsCommandInformation.html#CodeFactory_WinVs_Commands_IVsCommandInformation_CommandTitle
  name: CommandTitle
  nameWithType: IVsCommandInformation.CommandTitle
  fullName: CodeFactory.WinVs.Commands.IVsCommandInformation.CommandTitle
- uid: CodeFactory.WinVs.Commands.IVsCommandInformation.CommandDescription
  commentId: P:CodeFactory.WinVs.Commands.IVsCommandInformation.CommandDescription
  parent: CodeFactory.WinVs.Commands.IVsCommandInformation
  isExternal: true
  href: CodeFactory.WinVs.Commands.IVsCommandInformation.html#CodeFactory_WinVs_Commands_IVsCommandInformation_CommandDescription
  name: CommandDescription
  nameWithType: IVsCommandInformation.CommandDescription
  fullName: CodeFactory.WinVs.Commands.IVsCommandInformation.CommandDescription
- uid: CodeFactory.WinVs.Commands.IVsCommandInformation.CommandType
  commentId: P:CodeFactory.WinVs.Commands.IVsCommandInformation.CommandType
  parent: CodeFactory.WinVs.Commands.IVsCommandInformation
  isExternal: true
  href: CodeFactory.WinVs.Commands.IVsCommandInformation.html#CodeFactory_WinVs_Commands_IVsCommandInformation_CommandType
  name: CommandType
  nameWithType: IVsCommandInformation.CommandType
  fullName: CodeFactory.WinVs.Commands.IVsCommandInformation.CommandType
- uid: CodeFactory.ICommand{{TModel}}.EnableCommandAsync({TModel})
  commentId: M:CodeFactory.ICommand{`0}.EnableCommandAsync(`0)
  parent: CodeFactory.ICommand{{TModel}}
  definition: CodeFactory.ICommand`1.EnableCommandAsync(`0)
  href: https://github.com/CodeFactoryLLC/CodeFactoryForWindows/blob/19e816ffdf1ba504be6987736bbac42e2d241405/Src/CodeFactoryForWindows/CodeFactory/ICommand.cs
  name: EnableCommandAsync(TModel)
  nameWithType: ICommand<TModel>.EnableCommandAsync(TModel)
  fullName: CodeFactory.ICommand<TModel>.EnableCommandAsync(TModel)
  nameWithType.vb: ICommand(Of TModel).EnableCommandAsync(TModel)
  fullName.vb: CodeFactory.ICommand(Of TModel).EnableCommandAsync(TModel)
  spec.csharp:
  - uid: CodeFactory.ICommand{`0}.EnableCommandAsync(`0)
    name: EnableCommandAsync
    isExternal: true
    href: https://github.com/CodeFactoryLLC/CodeFactoryForWindows/blob/19e816ffdf1ba504be6987736bbac42e2d241405/Src/CodeFactoryForWindows/CodeFactory/ICommand.cs
  - name: (
  - name: TModel
  - name: )
  spec.vb:
  - uid: CodeFactory.ICommand{`0}.EnableCommandAsync(`0)
    name: EnableCommandAsync
    isExternal: true
    href: https://github.com/CodeFactoryLLC/CodeFactoryForWindows/blob/19e816ffdf1ba504be6987736bbac42e2d241405/Src/CodeFactoryForWindows/CodeFactory/ICommand.cs
  - name: (
  - name: TModel
  - name: )
- uid: CodeFactory.ICommandBase{{TModel}}.ExecuteCommandAsync({TModel})
  commentId: M:CodeFactory.ICommandBase{`0}.ExecuteCommandAsync(`0)
  parent: CodeFactory.ICommandBase{{TModel}}
  definition: CodeFactory.ICommandBase`1.ExecuteCommandAsync(`0)
  href: CodeFactory.ICommandBase-1.html#CodeFactory_ICommandBase_1_ExecuteCommandAsync__0_
  name: ExecuteCommandAsync(TModel)
  nameWithType: ICommandBase<TModel>.ExecuteCommandAsync(TModel)
  fullName: CodeFactory.ICommandBase<TModel>.ExecuteCommandAsync(TModel)
  nameWithType.vb: ICommandBase(Of TModel).ExecuteCommandAsync(TModel)
  fullName.vb: CodeFactory.ICommandBase(Of TModel).ExecuteCommandAsync(TModel)
  spec.csharp:
  - uid: CodeFactory.ICommandBase{`0}.ExecuteCommandAsync(`0)
    name: ExecuteCommandAsync
    isExternal: true
    href: CodeFactory.ICommandBase-1.html#CodeFactory_ICommandBase_1_ExecuteCommandAsync__0_
  - name: (
  - name: TModel
  - name: )
  spec.vb:
  - uid: CodeFactory.ICommandBase{`0}.ExecuteCommandAsync(`0)
    name: ExecuteCommandAsync
    isExternal: true
    href: CodeFactory.ICommandBase-1.html#CodeFactory_ICommandBase_1_ExecuteCommandAsync__0_
  - name: (
  - name: TModel
  - name: )
- uid: CodeFactory.WinVs.Commands.IVsFactoryCommand`1.VisualStudioActions
  commentId: P:CodeFactory.WinVs.Commands.IVsFactoryCommand`1.VisualStudioActions
  isExternal: true
  href: CodeFactory.WinVs.Commands.IVsFactoryCommand-1.html#CodeFactory_WinVs_Commands_IVsFactoryCommand_1_VisualStudioActions
  name: VisualStudioActions
  nameWithType: IVsFactoryCommand<TModel>.VisualStudioActions
  fullName: CodeFactory.WinVs.Commands.IVsFactoryCommand<TModel>.VisualStudioActions
  nameWithType.vb: IVsFactoryCommand(Of TModel).VisualStudioActions
  fullName.vb: CodeFactory.WinVs.Commands.IVsFactoryCommand(Of TModel).VisualStudioActions
- uid: CodeFactory.WinVs.Commands.IVsFactoryCommand{{TModel}}
  commentId: T:CodeFactory.WinVs.Commands.IVsFactoryCommand{`0}
  parent: CodeFactory.WinVs.Commands
  definition: CodeFactory.WinVs.Commands.IVsFactoryCommand`1
  href: CodeFactory.WinVs.Commands.IVsFactoryCommand-1.html
  name: IVsFactoryCommand<TModel>
  nameWithType: IVsFactoryCommand<TModel>
  fullName: CodeFactory.WinVs.Commands.IVsFactoryCommand<TModel>
  nameWithType.vb: IVsFactoryCommand(Of TModel)
  fullName.vb: CodeFactory.WinVs.Commands.IVsFactoryCommand(Of TModel)
  name.vb: IVsFactoryCommand(Of TModel)
  spec.csharp:
  - uid: CodeFactory.WinVs.Commands.IVsFactoryCommand`1
    name: IVsFactoryCommand
    isExternal: true
    href: CodeFactory.WinVs.Commands.IVsFactoryCommand-1.html
  - name: <
  - name: TModel
  - name: '>'
  spec.vb:
  - uid: CodeFactory.WinVs.Commands.IVsFactoryCommand`1
    name: IVsFactoryCommand
    isExternal: true
    href: CodeFactory.WinVs.Commands.IVsFactoryCommand-1.html
  - name: (
  - name: Of
  - name: " "
  - name: TModel
  - name: )
- uid: CodeFactory.WinVs.Commands.IVsCommandInformation
  commentId: T:CodeFactory.WinVs.Commands.IVsCommandInformation
  parent: CodeFactory.WinVs.Commands
  isExternal: true
  href: CodeFactory.WinVs.Commands.IVsCommandInformation.html
  name: IVsCommandInformation
  nameWithType: IVsCommandInformation
  fullName: CodeFactory.WinVs.Commands.IVsCommandInformation
- uid: CodeFactory.ICommand`1.EnableCommandAsync(`0)
  commentId: M:CodeFactory.ICommand`1.EnableCommandAsync(`0)
  isExternal: true
  href: https://github.com/CodeFactoryLLC/CodeFactoryForWindows/blob/19e816ffdf1ba504be6987736bbac42e2d241405/Src/CodeFactoryForWindows/CodeFactory/ICommand.cs
  name: EnableCommandAsync(TModel)
  nameWithType: ICommand<TModel>.EnableCommandAsync(TModel)
  fullName: CodeFactory.ICommand<TModel>.EnableCommandAsync(TModel)
  nameWithType.vb: ICommand(Of TModel).EnableCommandAsync(TModel)
  fullName.vb: CodeFactory.ICommand(Of TModel).EnableCommandAsync(TModel)
  spec.csharp:
  - uid: CodeFactory.ICommand`1.EnableCommandAsync(`0)
    name: EnableCommandAsync
    isExternal: true
    href: https://github.com/CodeFactoryLLC/CodeFactoryForWindows/blob/19e816ffdf1ba504be6987736bbac42e2d241405/Src/CodeFactoryForWindows/CodeFactory/ICommand.cs
  - name: (
  - name: TModel
  - name: )
  spec.vb:
  - uid: CodeFactory.ICommand`1.EnableCommandAsync(`0)
    name: EnableCommandAsync
    isExternal: true
    href: https://github.com/CodeFactoryLLC/CodeFactoryForWindows/blob/19e816ffdf1ba504be6987736bbac42e2d241405/Src/CodeFactoryForWindows/CodeFactory/ICommand.cs
  - name: (
  - name: TModel
  - name: )
- uid: CodeFactory.ICommand{{TModel}}
  commentId: T:CodeFactory.ICommand{`0}
  parent: CodeFactory
  definition: CodeFactory.ICommand`1
  href: https://github.com/CodeFactoryLLC/CodeFactoryForWindows/blob/19e816ffdf1ba504be6987736bbac42e2d241405/Src/CodeFactoryForWindows/CodeFactory/ICommand.cs
  name: ICommand<TModel>
  nameWithType: ICommand<TModel>
  fullName: CodeFactory.ICommand<TModel>
  nameWithType.vb: ICommand(Of TModel)
  fullName.vb: CodeFactory.ICommand(Of TModel)
  name.vb: ICommand(Of TModel)
  spec.csharp:
  - uid: CodeFactory.ICommand`1
    name: ICommand
    isExternal: true
    href: https://github.com/CodeFactoryLLC/CodeFactoryForWindows/blob/19e816ffdf1ba504be6987736bbac42e2d241405/Src/CodeFactoryForWindows/CodeFactory/ICommand.cs
  - name: <
  - name: TModel
  - name: '>'
  spec.vb:
  - uid: CodeFactory.ICommand`1
    name: ICommand
    isExternal: true
    href: https://github.com/CodeFactoryLLC/CodeFactoryForWindows/blob/19e816ffdf1ba504be6987736bbac42e2d241405/Src/CodeFactoryForWindows/CodeFactory/ICommand.cs
  - name: (
  - name: Of
  - name: " "
  - name: TModel
  - name: )
- uid: CodeFactory.ICommandBase`1.ExecuteCommandAsync(`0)
  commentId: M:CodeFactory.ICommandBase`1.ExecuteCommandAsync(`0)
  isExternal: true
  href: CodeFactory.ICommandBase-1.html#CodeFactory_ICommandBase_1_ExecuteCommandAsync__0_
  name: ExecuteCommandAsync(TModel)
  nameWithType: ICommandBase<TModel>.ExecuteCommandAsync(TModel)
  fullName: CodeFactory.ICommandBase<TModel>.ExecuteCommandAsync(TModel)
  nameWithType.vb: ICommandBase(Of TModel).ExecuteCommandAsync(TModel)
  fullName.vb: CodeFactory.ICommandBase(Of TModel).ExecuteCommandAsync(TModel)
  spec.csharp:
  - uid: CodeFactory.ICommandBase`1.ExecuteCommandAsync(`0)
    name: ExecuteCommandAsync
    isExternal: true
    href: CodeFactory.ICommandBase-1.html#CodeFactory_ICommandBase_1_ExecuteCommandAsync__0_
  - name: (
  - name: TModel
  - name: )
  spec.vb:
  - uid: CodeFactory.ICommandBase`1.ExecuteCommandAsync(`0)
    name: ExecuteCommandAsync
    isExternal: true
    href: CodeFactory.ICommandBase-1.html#CodeFactory_ICommandBase_1_ExecuteCommandAsync__0_
  - name: (
  - name: TModel
  - name: )
- uid: CodeFactory.ICommandBase{{TModel}}
  commentId: T:CodeFactory.ICommandBase{`0}
  parent: CodeFactory
  definition: CodeFactory.ICommandBase`1
  href: CodeFactory.ICommandBase-1.html
  name: ICommandBase<TModel>
  nameWithType: ICommandBase<TModel>
  fullName: CodeFactory.ICommandBase<TModel>
  nameWithType.vb: ICommandBase(Of TModel)
  fullName.vb: CodeFactory.ICommandBase(Of TModel)
  name.vb: ICommandBase(Of TModel)
  spec.csharp:
  - uid: CodeFactory.ICommandBase`1
    name: ICommandBase
    isExternal: true
    href: CodeFactory.ICommandBase-1.html
  - name: <
  - name: TModel
  - name: '>'
  spec.vb:
  - uid: CodeFactory.ICommandBase`1
    name: ICommandBase
    isExternal: true
    href: CodeFactory.ICommandBase-1.html
  - name: (
  - name: Of
  - name: " "
  - name: TModel
  - name: )
- uid: CodeFactory.WinVs.Commands.IVsFactoryCommand`1
  commentId: T:CodeFactory.WinVs.Commands.IVsFactoryCommand`1
  isExternal: true
  href: CodeFactory.WinVs.Commands.IVsFactoryCommand-1.html
  name: IVsFactoryCommand<TModel>
  nameWithType: IVsFactoryCommand<TModel>
  fullName: CodeFactory.WinVs.Commands.IVsFactoryCommand<TModel>
  nameWithType.vb: IVsFactoryCommand(Of TModel)
  fullName.vb: CodeFactory.WinVs.Commands.IVsFactoryCommand(Of TModel)
  name.vb: IVsFactoryCommand(Of TModel)
  spec.csharp:
  - uid: CodeFactory.WinVs.Commands.IVsFactoryCommand`1
    name: IVsFactoryCommand
    isExternal: true
    href: CodeFactory.WinVs.Commands.IVsFactoryCommand-1.html
  - name: <
  - name: TModel
  - name: '>'
  spec.vb:
  - uid: CodeFactory.WinVs.Commands.IVsFactoryCommand`1
    name: IVsFactoryCommand
    isExternal: true
    href: CodeFactory.WinVs.Commands.IVsFactoryCommand-1.html
  - name: (
  - name: Of
  - name: " "
  - name: TModel
  - name: )
- uid: CodeFactory.ICommand`1
  commentId: T:CodeFactory.ICommand`1
  isExternal: true
  href: CodeFactory.ICommand-1.html
  name: ICommand<TModel>
  nameWithType: ICommand<TModel>
  fullName: CodeFactory.ICommand<TModel>
  nameWithType.vb: ICommand(Of TModel)
  fullName.vb: CodeFactory.ICommand(Of TModel)
  name.vb: ICommand(Of TModel)
  spec.csharp:
  - uid: CodeFactory.ICommand`1
    name: ICommand
    isExternal: true
    href: CodeFactory.ICommand-1.html
  - name: <
  - name: TModel
  - name: '>'
  spec.vb:
  - uid: CodeFactory.ICommand`1
    name: ICommand
    isExternal: true
    href: CodeFactory.ICommand-1.html
  - name: (
  - name: Of
  - name: " "
  - name: TModel
  - name: )
- uid: CodeFactory
  commentId: N:CodeFactory
  isExternal: true
  href: CodeFactory.html
  name: CodeFactory
  nameWithType: CodeFactory
  fullName: CodeFactory
- uid: CodeFactory.ICommandBase`1
  commentId: T:CodeFactory.ICommandBase`1
  isExternal: true
  href: CodeFactory.ICommandBase-1.html
  name: ICommandBase<TModel>
  nameWithType: ICommandBase<TModel>
  fullName: CodeFactory.ICommandBase<TModel>
  nameWithType.vb: ICommandBase(Of TModel)
  fullName.vb: CodeFactory.ICommandBase(Of TModel)
  name.vb: ICommandBase(Of TModel)
  spec.csharp:
  - uid: CodeFactory.ICommandBase`1
    name: ICommandBase
    isExternal: true
    href: CodeFactory.ICommandBase-1.html
  - name: <
  - name: TModel
  - name: '>'
  spec.vb:
  - uid: CodeFactory.ICommandBase`1
    name: ICommandBase
    isExternal: true
    href: CodeFactory.ICommandBase-1.html
  - name: (
  - name: Of
  - name: " "
  - name: TModel
  - name: )
- uid: CodeFactory.WinVs.Commands.IVsConfigurableCommand`1.LoadExternalConfigDefinition*
  commentId: Overload:CodeFactory.WinVs.Commands.IVsConfigurableCommand`1.LoadExternalConfigDefinition
  isExternal: true
  href: CodeFactory.WinVs.Commands.IVsConfigurableCommand-1.html#CodeFactory_WinVs_Commands_IVsConfigurableCommand_1_LoadExternalConfigDefinition
  name: LoadExternalConfigDefinition
  nameWithType: IVsConfigurableCommand<TModel>.LoadExternalConfigDefinition
  fullName: CodeFactory.WinVs.Commands.IVsConfigurableCommand<TModel>.LoadExternalConfigDefinition
  nameWithType.vb: IVsConfigurableCommand(Of TModel).LoadExternalConfigDefinition
  fullName.vb: CodeFactory.WinVs.Commands.IVsConfigurableCommand(Of TModel).LoadExternalConfigDefinition
- uid: CodeFactory.WinVs.Commands.ConfigCommand
  commentId: T:CodeFactory.WinVs.Commands.ConfigCommand
  parent: CodeFactory.WinVs.Commands
  isExternal: true
  href: CodeFactory.WinVs.Commands.ConfigCommand.html
  name: ConfigCommand
  nameWithType: ConfigCommand
  fullName: CodeFactory.WinVs.Commands.ConfigCommand
