### YamlMime:ManagedReference
items:
- uid: CodeFactory.WinVs.Models.CSharp.CsSecurity
  commentId: T:CodeFactory.WinVs.Models.CSharp.CsSecurity
  id: CsSecurity
  parent: CodeFactory.WinVs.Models.CSharp
  children:
  - CodeFactory.WinVs.Models.CSharp.CsSecurity.Internal
  - CodeFactory.WinVs.Models.CSharp.CsSecurity.Private
  - CodeFactory.WinVs.Models.CSharp.CsSecurity.Protected
  - CodeFactory.WinVs.Models.CSharp.CsSecurity.ProtectedInternal
  - CodeFactory.WinVs.Models.CSharp.CsSecurity.ProtectedOrInternal
  - CodeFactory.WinVs.Models.CSharp.CsSecurity.Public
  - CodeFactory.WinVs.Models.CSharp.CsSecurity.Unknown
  langs:
  - csharp
  - vb
  name: CsSecurity
  nameWithType: CsSecurity
  fullName: CodeFactory.WinVs.Models.CSharp.CsSecurity
  type: Enum
  source:
    href: https://github.com/CodeFactoryLLC/CodeFactoryForWindows/blob/e63c05962945f61f2329e19d324f24a768806f18/Src/CodeFactoryForWindows/CodeFactory.WinVs/Models/CSharp/CsSecurity.cs
  assemblies:
  - CodeFactory.WinVs
  namespace: CodeFactory.WinVs.Models.CSharp
  summary: Enumeration that determines the security scope of the C# model being represented.
  example: []
  syntax:
    content: public enum CsSecurity
    content.vb: Public Enum CsSecurity
  extensionMethods:
  - CodeFactory.WinVs.Models.CSharp.CsSecurity.CodeFactory.WinVs.Models.CSharp.GenerateCSharpCsSecurityExtensions.GenerateCSharpKeyword
- uid: CodeFactory.WinVs.Models.CSharp.CsSecurity.Public
  commentId: F:CodeFactory.WinVs.Models.CSharp.CsSecurity.Public
  id: Public
  parent: CodeFactory.WinVs.Models.CSharp.CsSecurity
  langs:
  - csharp
  - vb
  name: Public
  nameWithType: CsSecurity.Public
  fullName: CodeFactory.WinVs.Models.CSharp.CsSecurity.Public
  type: Field
  source:
    href: https://github.com/CodeFactoryLLC/CodeFactoryForWindows/blob/e63c05962945f61f2329e19d324f24a768806f18/Src/CodeFactoryForWindows/CodeFactory.WinVs/Models/CSharp/CsSecurity.cs
  assemblies:
  - CodeFactory.WinVs
  namespace: CodeFactory.WinVs.Models.CSharp
  summary: Security is set to public access
  example: []
  syntax:
    content: Public = 0
    return:
      type: CodeFactory.WinVs.Models.CSharp.CsSecurity
- uid: CodeFactory.WinVs.Models.CSharp.CsSecurity.Protected
  commentId: F:CodeFactory.WinVs.Models.CSharp.CsSecurity.Protected
  id: Protected
  parent: CodeFactory.WinVs.Models.CSharp.CsSecurity
  langs:
  - csharp
  - vb
  name: Protected
  nameWithType: CsSecurity.Protected
  fullName: CodeFactory.WinVs.Models.CSharp.CsSecurity.Protected
  type: Field
  source:
    href: https://github.com/CodeFactoryLLC/CodeFactoryForWindows/blob/e63c05962945f61f2329e19d324f24a768806f18/Src/CodeFactoryForWindows/CodeFactory.WinVs/Models/CSharp/CsSecurity.cs
  assemblies:
  - CodeFactory.WinVs
  namespace: CodeFactory.WinVs.Models.CSharp
  summary: Security is set to protected access
  example: []
  syntax:
    content: Protected = 1
    return:
      type: CodeFactory.WinVs.Models.CSharp.CsSecurity
- uid: CodeFactory.WinVs.Models.CSharp.CsSecurity.Internal
  commentId: F:CodeFactory.WinVs.Models.CSharp.CsSecurity.Internal
  id: Internal
  parent: CodeFactory.WinVs.Models.CSharp.CsSecurity
  langs:
  - csharp
  - vb
  name: Internal
  nameWithType: CsSecurity.Internal
  fullName: CodeFactory.WinVs.Models.CSharp.CsSecurity.Internal
  type: Field
  source:
    href: https://github.com/CodeFactoryLLC/CodeFactoryForWindows/blob/e63c05962945f61f2329e19d324f24a768806f18/Src/CodeFactoryForWindows/CodeFactory.WinVs/Models/CSharp/CsSecurity.cs
  assemblies:
  - CodeFactory.WinVs
  namespace: CodeFactory.WinVs.Models.CSharp
  summary: Security is set to internal access
  example: []
  syntax:
    content: Internal = 2
    return:
      type: CodeFactory.WinVs.Models.CSharp.CsSecurity
- uid: CodeFactory.WinVs.Models.CSharp.CsSecurity.Private
  commentId: F:CodeFactory.WinVs.Models.CSharp.CsSecurity.Private
  id: Private
  parent: CodeFactory.WinVs.Models.CSharp.CsSecurity
  langs:
  - csharp
  - vb
  name: Private
  nameWithType: CsSecurity.Private
  fullName: CodeFactory.WinVs.Models.CSharp.CsSecurity.Private
  type: Field
  source:
    href: https://github.com/CodeFactoryLLC/CodeFactoryForWindows/blob/e63c05962945f61f2329e19d324f24a768806f18/Src/CodeFactoryForWindows/CodeFactory.WinVs/Models/CSharp/CsSecurity.cs
  assemblies:
  - CodeFactory.WinVs
  namespace: CodeFactory.WinVs.Models.CSharp
  summary: Security is set to private access
  example: []
  syntax:
    content: Private = 3
    return:
      type: CodeFactory.WinVs.Models.CSharp.CsSecurity
- uid: CodeFactory.WinVs.Models.CSharp.CsSecurity.ProtectedInternal
  commentId: F:CodeFactory.WinVs.Models.CSharp.CsSecurity.ProtectedInternal
  id: ProtectedInternal
  parent: CodeFactory.WinVs.Models.CSharp.CsSecurity
  langs:
  - csharp
  - vb
  name: ProtectedInternal
  nameWithType: CsSecurity.ProtectedInternal
  fullName: CodeFactory.WinVs.Models.CSharp.CsSecurity.ProtectedInternal
  type: Field
  source:
    href: https://github.com/CodeFactoryLLC/CodeFactoryForWindows/blob/e63c05962945f61f2329e19d324f24a768806f18/Src/CodeFactoryForWindows/CodeFactory.WinVs/Models/CSharp/CsSecurity.cs
  assemblies:
  - CodeFactory.WinVs
  namespace: CodeFactory.WinVs.Models.CSharp
  summary: Security is set to protected internal access
  example: []
  syntax:
    content: ProtectedInternal = 4
    return:
      type: CodeFactory.WinVs.Models.CSharp.CsSecurity
- uid: CodeFactory.WinVs.Models.CSharp.CsSecurity.ProtectedOrInternal
  commentId: F:CodeFactory.WinVs.Models.CSharp.CsSecurity.ProtectedOrInternal
  id: ProtectedOrInternal
  parent: CodeFactory.WinVs.Models.CSharp.CsSecurity
  langs:
  - csharp
  - vb
  name: ProtectedOrInternal
  nameWithType: CsSecurity.ProtectedOrInternal
  fullName: CodeFactory.WinVs.Models.CSharp.CsSecurity.ProtectedOrInternal
  type: Field
  source:
    href: https://github.com/CodeFactoryLLC/CodeFactoryForWindows/blob/e63c05962945f61f2329e19d324f24a768806f18/Src/CodeFactoryForWindows/CodeFactory.WinVs/Models/CSharp/CsSecurity.cs
  assemblies:
  - CodeFactory.WinVs
  namespace: CodeFactory.WinVs.Models.CSharp
  summary: Security is set to projected or internal access
  example: []
  syntax:
    content: ProtectedOrInternal = 5
    return:
      type: CodeFactory.WinVs.Models.CSharp.CsSecurity
- uid: CodeFactory.WinVs.Models.CSharp.CsSecurity.Unknown
  commentId: F:CodeFactory.WinVs.Models.CSharp.CsSecurity.Unknown
  id: Unknown
  parent: CodeFactory.WinVs.Models.CSharp.CsSecurity
  langs:
  - csharp
  - vb
  name: Unknown
  nameWithType: CsSecurity.Unknown
  fullName: CodeFactory.WinVs.Models.CSharp.CsSecurity.Unknown
  type: Field
  source:
    href: https://github.com/CodeFactoryLLC/CodeFactoryForWindows/blob/e63c05962945f61f2329e19d324f24a768806f18/Src/CodeFactoryForWindows/CodeFactory.WinVs/Models/CSharp/CsSecurity.cs
  assemblies:
  - CodeFactory.WinVs
  namespace: CodeFactory.WinVs.Models.CSharp
  summary: Security scope is unknown
  example: []
  syntax:
    content: Unknown = 9999
    return:
      type: CodeFactory.WinVs.Models.CSharp.CsSecurity
references:
- uid: CodeFactory.WinVs.Models.CSharp
  commentId: N:CodeFactory.WinVs.Models.CSharp
  isExternal: true
  href: CodeFactory.html
  name: CodeFactory.WinVs.Models.CSharp
  nameWithType: CodeFactory.WinVs.Models.CSharp
  fullName: CodeFactory.WinVs.Models.CSharp
  spec.csharp:
  - uid: CodeFactory
    name: CodeFactory
    isExternal: true
    href: CodeFactory.html
  - name: .
  - uid: CodeFactory.WinVs
    name: WinVs
    isExternal: true
    href: CodeFactory.WinVs.html
  - name: .
  - uid: CodeFactory.WinVs.Models
    name: Models
    isExternal: true
    href: CodeFactory.WinVs.Models.html
  - name: .
  - uid: CodeFactory.WinVs.Models.CSharp
    name: CSharp
    isExternal: true
    href: CodeFactory.WinVs.Models.CSharp.html
  spec.vb:
  - uid: CodeFactory
    name: CodeFactory
    isExternal: true
    href: CodeFactory.html
  - name: .
  - uid: CodeFactory.WinVs
    name: WinVs
    isExternal: true
    href: CodeFactory.WinVs.html
  - name: .
  - uid: CodeFactory.WinVs.Models
    name: Models
    isExternal: true
    href: CodeFactory.WinVs.Models.html
  - name: .
  - uid: CodeFactory.WinVs.Models.CSharp
    name: CSharp
    isExternal: true
    href: CodeFactory.WinVs.Models.CSharp.html
- uid: CodeFactory.WinVs.Models.CSharp.CsSecurity.CodeFactory.WinVs.Models.CSharp.GenerateCSharpCsSecurityExtensions.GenerateCSharpKeyword
  commentId: M:CodeFactory.WinVs.Models.CSharp.GenerateCSharpCsSecurityExtensions.GenerateCSharpKeyword(CodeFactory.WinVs.Models.CSharp.CsSecurity)
  parent: CodeFactory.WinVs.Models.CSharp.GenerateCSharpCsSecurityExtensions
  definition: CodeFactory.WinVs.Models.CSharp.GenerateCSharpCsSecurityExtensions.GenerateCSharpKeyword(CodeFactory.WinVs.Models.CSharp.CsSecurity)
  href: CodeFactory.WinVs.Models.CSharp.GenerateCSharpCsSecurityExtensions.html#CodeFactory_WinVs_Models_CSharp_GenerateCSharpCsSecurityExtensions_GenerateCSharpKeyword_CodeFactory_WinVs_Models_CSharp_CsSecurity_
  name: GenerateCSharpKeyword(CsSecurity)
  nameWithType: GenerateCSharpCsSecurityExtensions.GenerateCSharpKeyword(CsSecurity)
  fullName: CodeFactory.WinVs.Models.CSharp.GenerateCSharpCsSecurityExtensions.GenerateCSharpKeyword(CodeFactory.WinVs.Models.CSharp.CsSecurity)
  spec.csharp:
  - uid: CodeFactory.WinVs.Models.CSharp.GenerateCSharpCsSecurityExtensions.GenerateCSharpKeyword(CodeFactory.WinVs.Models.CSharp.CsSecurity)
    name: GenerateCSharpKeyword
    isExternal: true
    href: CodeFactory.WinVs.Models.CSharp.GenerateCSharpCsSecurityExtensions.html#CodeFactory_WinVs_Models_CSharp_GenerateCSharpCsSecurityExtensions_GenerateCSharpKeyword_CodeFactory_WinVs_Models_CSharp_CsSecurity_
  - name: (
  - uid: CodeFactory.WinVs.Models.CSharp.CsSecurity
    name: CsSecurity
    isExternal: true
    href: CodeFactory.WinVs.Models.CSharp.CsSecurity.html
  - name: )
  spec.vb:
  - uid: CodeFactory.WinVs.Models.CSharp.GenerateCSharpCsSecurityExtensions.GenerateCSharpKeyword(CodeFactory.WinVs.Models.CSharp.CsSecurity)
    name: GenerateCSharpKeyword
    isExternal: true
    href: CodeFactory.WinVs.Models.CSharp.GenerateCSharpCsSecurityExtensions.html#CodeFactory_WinVs_Models_CSharp_GenerateCSharpCsSecurityExtensions_GenerateCSharpKeyword_CodeFactory_WinVs_Models_CSharp_CsSecurity_
  - name: (
  - uid: CodeFactory.WinVs.Models.CSharp.CsSecurity
    name: CsSecurity
    isExternal: true
    href: CodeFactory.WinVs.Models.CSharp.CsSecurity.html
  - name: )
- uid: CodeFactory.WinVs.Models.CSharp.GenerateCSharpCsSecurityExtensions.GenerateCSharpKeyword(CodeFactory.WinVs.Models.CSharp.CsSecurity)
  commentId: M:CodeFactory.WinVs.Models.CSharp.GenerateCSharpCsSecurityExtensions.GenerateCSharpKeyword(CodeFactory.WinVs.Models.CSharp.CsSecurity)
  isExternal: true
  href: CodeFactory.WinVs.Models.CSharp.GenerateCSharpCsSecurityExtensions.html#CodeFactory_WinVs_Models_CSharp_GenerateCSharpCsSecurityExtensions_GenerateCSharpKeyword_CodeFactory_WinVs_Models_CSharp_CsSecurity_
  name: GenerateCSharpKeyword(CsSecurity)
  nameWithType: GenerateCSharpCsSecurityExtensions.GenerateCSharpKeyword(CsSecurity)
  fullName: CodeFactory.WinVs.Models.CSharp.GenerateCSharpCsSecurityExtensions.GenerateCSharpKeyword(CodeFactory.WinVs.Models.CSharp.CsSecurity)
  spec.csharp:
  - uid: CodeFactory.WinVs.Models.CSharp.GenerateCSharpCsSecurityExtensions.GenerateCSharpKeyword(CodeFactory.WinVs.Models.CSharp.CsSecurity)
    name: GenerateCSharpKeyword
    isExternal: true
    href: CodeFactory.WinVs.Models.CSharp.GenerateCSharpCsSecurityExtensions.html#CodeFactory_WinVs_Models_CSharp_GenerateCSharpCsSecurityExtensions_GenerateCSharpKeyword_CodeFactory_WinVs_Models_CSharp_CsSecurity_
  - name: (
  - uid: CodeFactory.WinVs.Models.CSharp.CsSecurity
    name: CsSecurity
    isExternal: true
    href: CodeFactory.WinVs.Models.CSharp.CsSecurity.html
  - name: )
  spec.vb:
  - uid: CodeFactory.WinVs.Models.CSharp.GenerateCSharpCsSecurityExtensions.GenerateCSharpKeyword(CodeFactory.WinVs.Models.CSharp.CsSecurity)
    name: GenerateCSharpKeyword
    isExternal: true
    href: CodeFactory.WinVs.Models.CSharp.GenerateCSharpCsSecurityExtensions.html#CodeFactory_WinVs_Models_CSharp_GenerateCSharpCsSecurityExtensions_GenerateCSharpKeyword_CodeFactory_WinVs_Models_CSharp_CsSecurity_
  - name: (
  - uid: CodeFactory.WinVs.Models.CSharp.CsSecurity
    name: CsSecurity
    isExternal: true
    href: CodeFactory.WinVs.Models.CSharp.CsSecurity.html
  - name: )
- uid: CodeFactory.WinVs.Models.CSharp.GenerateCSharpCsSecurityExtensions
  commentId: T:CodeFactory.WinVs.Models.CSharp.GenerateCSharpCsSecurityExtensions
  parent: CodeFactory.WinVs.Models.CSharp
  isExternal: true
  href: CodeFactory.WinVs.Models.CSharp.GenerateCSharpCsSecurityExtensions.html
  name: GenerateCSharpCsSecurityExtensions
  nameWithType: GenerateCSharpCsSecurityExtensions
  fullName: CodeFactory.WinVs.Models.CSharp.GenerateCSharpCsSecurityExtensions
- uid: CodeFactory.WinVs.Models.CSharp.CsSecurity
  commentId: T:CodeFactory.WinVs.Models.CSharp.CsSecurity
  parent: CodeFactory.WinVs.Models.CSharp
  isExternal: true
  href: CodeFactory.WinVs.Models.CSharp.CsSecurity.html
  name: CsSecurity
  nameWithType: CsSecurity
  fullName: CodeFactory.WinVs.Models.CSharp.CsSecurity
