### YamlMime:ManagedReference
items:
- uid: CodeFactory.WinVs.Loader.IVsLibraryConfiguration
  commentId: T:CodeFactory.WinVs.Loader.IVsLibraryConfiguration
  id: IVsLibraryConfiguration
  parent: CodeFactory.WinVs.Loader
  children:
  - CodeFactory.WinVs.Loader.IVsLibraryConfiguration.AssemblyFilePath
  - CodeFactory.WinVs.Loader.IVsLibraryConfiguration.AssemblyStrongName
  - CodeFactory.WinVs.Loader.IVsLibraryConfiguration.ErrorDetails
  - CodeFactory.WinVs.Loader.IVsLibraryConfiguration.ErrorType
  - CodeFactory.WinVs.Loader.IVsLibraryConfiguration.HasDebugInformation
  - CodeFactory.WinVs.Loader.IVsLibraryConfiguration.HasErrors
  - CodeFactory.WinVs.Loader.IVsLibraryConfiguration.IsStoredInGac
  langs:
  - csharp
  - vb
  name: IVsLibraryConfiguration
  nameWithType: IVsLibraryConfiguration
  fullName: CodeFactory.WinVs.Loader.IVsLibraryConfiguration
  type: Interface
  source:
    href: https://github.com/CodeFactoryLLC/CodeFactoryForWindows/blob/19e816ffdf1ba504be6987736bbac42e2d241405/Src/CodeFactoryForWindows/CodeFactory.WinVs/Loader/IVsLibraryConfiguration.cs
  assemblies:
  - CodeFactory.WinVs
  namespace: CodeFactory.WinVs.Loader
  summary: Data model that stores all the information needed to load a DLL into visual studio.
  example: []
  syntax:
    content: public interface IVsLibraryConfiguration
    content.vb: Public Interface IVsLibraryConfiguration
- uid: CodeFactory.WinVs.Loader.IVsLibraryConfiguration.IsStoredInGac
  commentId: P:CodeFactory.WinVs.Loader.IVsLibraryConfiguration.IsStoredInGac
  id: IsStoredInGac
  parent: CodeFactory.WinVs.Loader.IVsLibraryConfiguration
  langs:
  - csharp
  - vb
  name: IsStoredInGac
  nameWithType: IVsLibraryConfiguration.IsStoredInGac
  fullName: CodeFactory.WinVs.Loader.IVsLibraryConfiguration.IsStoredInGac
  type: Property
  source:
    href: https://github.com/CodeFactoryLLC/CodeFactoryForWindows/blob/19e816ffdf1ba504be6987736bbac42e2d241405/Src/CodeFactoryForWindows/CodeFactory.WinVs/Loader/IVsLibraryConfiguration.cs
  assemblies:
  - CodeFactory.WinVs
  namespace: CodeFactory.WinVs.Loader
  summary: Flag that determines if the assembly is stored in the Global Assembly Cache on the computer.
  example: []
  syntax:
    content: bool IsStoredInGac { get; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: ReadOnly Property IsStoredInGac As Boolean
  overload: CodeFactory.WinVs.Loader.IVsLibraryConfiguration.IsStoredInGac*
- uid: CodeFactory.WinVs.Loader.IVsLibraryConfiguration.HasErrors
  commentId: P:CodeFactory.WinVs.Loader.IVsLibraryConfiguration.HasErrors
  id: HasErrors
  parent: CodeFactory.WinVs.Loader.IVsLibraryConfiguration
  langs:
  - csharp
  - vb
  name: HasErrors
  nameWithType: IVsLibraryConfiguration.HasErrors
  fullName: CodeFactory.WinVs.Loader.IVsLibraryConfiguration.HasErrors
  type: Property
  source:
    href: https://github.com/CodeFactoryLLC/CodeFactoryForWindows/blob/19e816ffdf1ba504be6987736bbac42e2d241405/Src/CodeFactoryForWindows/CodeFactory.WinVs/Loader/IVsLibraryConfiguration.cs
  assemblies:
  - CodeFactory.WinVs
  namespace: CodeFactory.WinVs.Loader
  summary: Flag that determines if their were errors loading the library configuration.
  example: []
  syntax:
    content: bool HasErrors { get; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: ReadOnly Property HasErrors As Boolean
  overload: CodeFactory.WinVs.Loader.IVsLibraryConfiguration.HasErrors*
- uid: CodeFactory.WinVs.Loader.IVsLibraryConfiguration.ErrorType
  commentId: P:CodeFactory.WinVs.Loader.IVsLibraryConfiguration.ErrorType
  id: ErrorType
  parent: CodeFactory.WinVs.Loader.IVsLibraryConfiguration
  langs:
  - csharp
  - vb
  name: ErrorType
  nameWithType: IVsLibraryConfiguration.ErrorType
  fullName: CodeFactory.WinVs.Loader.IVsLibraryConfiguration.ErrorType
  type: Property
  source:
    href: https://github.com/CodeFactoryLLC/CodeFactoryForWindows/blob/19e816ffdf1ba504be6987736bbac42e2d241405/Src/CodeFactoryForWindows/CodeFactory.WinVs/Loader/IVsLibraryConfiguration.cs
  assemblies:
  - CodeFactory.WinVs
  namespace: CodeFactory.WinVs.Loader
  summary: Enumeration that stores the type of error that has occurred while loading the library configuration.
  example: []
  syntax:
    content: LibraryErrorType ErrorType { get; }
    parameters: []
    return:
      type: CodeFactory.WinVs.Loader.LibraryErrorType
    content.vb: ReadOnly Property ErrorType As LibraryErrorType
  overload: CodeFactory.WinVs.Loader.IVsLibraryConfiguration.ErrorType*
- uid: CodeFactory.WinVs.Loader.IVsLibraryConfiguration.ErrorDetails
  commentId: P:CodeFactory.WinVs.Loader.IVsLibraryConfiguration.ErrorDetails
  id: ErrorDetails
  parent: CodeFactory.WinVs.Loader.IVsLibraryConfiguration
  langs:
  - csharp
  - vb
  name: ErrorDetails
  nameWithType: IVsLibraryConfiguration.ErrorDetails
  fullName: CodeFactory.WinVs.Loader.IVsLibraryConfiguration.ErrorDetails
  type: Property
  source:
    href: https://github.com/CodeFactoryLLC/CodeFactoryForWindows/blob/19e816ffdf1ba504be6987736bbac42e2d241405/Src/CodeFactoryForWindows/CodeFactory.WinVs/Loader/IVsLibraryConfiguration.cs
  assemblies:
  - CodeFactory.WinVs
  namespace: CodeFactory.WinVs.Loader
  summary: Stores the exception message for the error.
  example: []
  syntax:
    content: string ErrorDetails { get; }
    parameters: []
    return:
      type: System.String
    content.vb: ReadOnly Property ErrorDetails As String
  overload: CodeFactory.WinVs.Loader.IVsLibraryConfiguration.ErrorDetails*
- uid: CodeFactory.WinVs.Loader.IVsLibraryConfiguration.AssemblyFilePath
  commentId: P:CodeFactory.WinVs.Loader.IVsLibraryConfiguration.AssemblyFilePath
  id: AssemblyFilePath
  parent: CodeFactory.WinVs.Loader.IVsLibraryConfiguration
  langs:
  - csharp
  - vb
  name: AssemblyFilePath
  nameWithType: IVsLibraryConfiguration.AssemblyFilePath
  fullName: CodeFactory.WinVs.Loader.IVsLibraryConfiguration.AssemblyFilePath
  type: Property
  source:
    href: https://github.com/CodeFactoryLLC/CodeFactoryForWindows/blob/19e816ffdf1ba504be6987736bbac42e2d241405/Src/CodeFactoryForWindows/CodeFactory.WinVs/Loader/IVsLibraryConfiguration.cs
  assemblies:
  - CodeFactory.WinVs
  namespace: CodeFactory.WinVs.Loader
  summary: File path to where the assembly is found. This will be null if the assembly is stored in the GAC.
  example: []
  syntax:
    content: string AssemblyFilePath { get; }
    parameters: []
    return:
      type: System.String
    content.vb: ReadOnly Property AssemblyFilePath As String
  overload: CodeFactory.WinVs.Loader.IVsLibraryConfiguration.AssemblyFilePath*
- uid: CodeFactory.WinVs.Loader.IVsLibraryConfiguration.AssemblyStrongName
  commentId: P:CodeFactory.WinVs.Loader.IVsLibraryConfiguration.AssemblyStrongName
  id: AssemblyStrongName
  parent: CodeFactory.WinVs.Loader.IVsLibraryConfiguration
  langs:
  - csharp
  - vb
  name: AssemblyStrongName
  nameWithType: IVsLibraryConfiguration.AssemblyStrongName
  fullName: CodeFactory.WinVs.Loader.IVsLibraryConfiguration.AssemblyStrongName
  type: Property
  source:
    href: https://github.com/CodeFactoryLLC/CodeFactoryForWindows/blob/19e816ffdf1ba504be6987736bbac42e2d241405/Src/CodeFactoryForWindows/CodeFactory.WinVs/Loader/IVsLibraryConfiguration.cs
  assemblies:
  - CodeFactory.WinVs
  namespace: CodeFactory.WinVs.Loader
  summary: The fully qualified name of the assembly to be loaded. This will be null if not stored in the GAC.
  example: []
  syntax:
    content: string AssemblyStrongName { get; }
    parameters: []
    return:
      type: System.String
    content.vb: ReadOnly Property AssemblyStrongName As String
  overload: CodeFactory.WinVs.Loader.IVsLibraryConfiguration.AssemblyStrongName*
- uid: CodeFactory.WinVs.Loader.IVsLibraryConfiguration.HasDebugInformation
  commentId: P:CodeFactory.WinVs.Loader.IVsLibraryConfiguration.HasDebugInformation
  id: HasDebugInformation
  parent: CodeFactory.WinVs.Loader.IVsLibraryConfiguration
  langs:
  - csharp
  - vb
  name: HasDebugInformation
  nameWithType: IVsLibraryConfiguration.HasDebugInformation
  fullName: CodeFactory.WinVs.Loader.IVsLibraryConfiguration.HasDebugInformation
  type: Property
  source:
    href: https://github.com/CodeFactoryLLC/CodeFactoryForWindows/blob/19e816ffdf1ba504be6987736bbac42e2d241405/Src/CodeFactoryForWindows/CodeFactory.WinVs/Loader/IVsLibraryConfiguration.cs
  assemblies:
  - CodeFactory.WinVs
  namespace: CodeFactory.WinVs.Loader
  summary: Flag that determines if the PDB file is found wit the assembly in the file path. This will be false if it is stored in the GAC.
  example: []
  syntax:
    content: bool HasDebugInformation { get; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: ReadOnly Property HasDebugInformation As Boolean
  overload: CodeFactory.WinVs.Loader.IVsLibraryConfiguration.HasDebugInformation*
references:
- uid: CodeFactory.WinVs.Loader
  commentId: N:CodeFactory.WinVs.Loader
  isExternal: true
  href: CodeFactory.html
  name: CodeFactory.WinVs.Loader
  nameWithType: CodeFactory.WinVs.Loader
  fullName: CodeFactory.WinVs.Loader
  spec.csharp:
  - uid: CodeFactory
    name: CodeFactory
    isExternal: true
    href: CodeFactory.html
  - name: .
  - uid: CodeFactory.WinVs
    name: WinVs
    isExternal: true
    href: CodeFactory.WinVs.html
  - name: .
  - uid: CodeFactory.WinVs.Loader
    name: Loader
    isExternal: true
    href: CodeFactory.WinVs.Loader.html
  spec.vb:
  - uid: CodeFactory
    name: CodeFactory
    isExternal: true
    href: CodeFactory.html
  - name: .
  - uid: CodeFactory.WinVs
    name: WinVs
    isExternal: true
    href: CodeFactory.WinVs.html
  - name: .
  - uid: CodeFactory.WinVs.Loader
    name: Loader
    isExternal: true
    href: CodeFactory.WinVs.Loader.html
- uid: CodeFactory.WinVs.Loader.IVsLibraryConfiguration.IsStoredInGac*
  commentId: Overload:CodeFactory.WinVs.Loader.IVsLibraryConfiguration.IsStoredInGac
  isExternal: true
  href: CodeFactory.WinVs.Loader.IVsLibraryConfiguration.html#CodeFactory_WinVs_Loader_IVsLibraryConfiguration_IsStoredInGac
  name: IsStoredInGac
  nameWithType: IVsLibraryConfiguration.IsStoredInGac
  fullName: CodeFactory.WinVs.Loader.IVsLibraryConfiguration.IsStoredInGac
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.boolean
  name: bool
  nameWithType: bool
  fullName: bool
  nameWithType.vb: Boolean
  fullName.vb: Boolean
  name.vb: Boolean
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: CodeFactory.WinVs.Loader.IVsLibraryConfiguration.HasErrors*
  commentId: Overload:CodeFactory.WinVs.Loader.IVsLibraryConfiguration.HasErrors
  isExternal: true
  href: CodeFactory.WinVs.Loader.IVsLibraryConfiguration.html#CodeFactory_WinVs_Loader_IVsLibraryConfiguration_HasErrors
  name: HasErrors
  nameWithType: IVsLibraryConfiguration.HasErrors
  fullName: CodeFactory.WinVs.Loader.IVsLibraryConfiguration.HasErrors
- uid: CodeFactory.WinVs.Loader.IVsLibraryConfiguration.ErrorType*
  commentId: Overload:CodeFactory.WinVs.Loader.IVsLibraryConfiguration.ErrorType
  isExternal: true
  href: CodeFactory.WinVs.Loader.IVsLibraryConfiguration.html#CodeFactory_WinVs_Loader_IVsLibraryConfiguration_ErrorType
  name: ErrorType
  nameWithType: IVsLibraryConfiguration.ErrorType
  fullName: CodeFactory.WinVs.Loader.IVsLibraryConfiguration.ErrorType
- uid: CodeFactory.WinVs.Loader.LibraryErrorType
  commentId: T:CodeFactory.WinVs.Loader.LibraryErrorType
  parent: CodeFactory.WinVs.Loader
  isExternal: true
  href: CodeFactory.WinVs.Loader.LibraryErrorType.html
  name: LibraryErrorType
  nameWithType: LibraryErrorType
  fullName: CodeFactory.WinVs.Loader.LibraryErrorType
- uid: CodeFactory.WinVs.Loader.IVsLibraryConfiguration.ErrorDetails*
  commentId: Overload:CodeFactory.WinVs.Loader.IVsLibraryConfiguration.ErrorDetails
  isExternal: true
  href: CodeFactory.WinVs.Loader.IVsLibraryConfiguration.html#CodeFactory_WinVs_Loader_IVsLibraryConfiguration_ErrorDetails
  name: ErrorDetails
  nameWithType: IVsLibraryConfiguration.ErrorDetails
  fullName: CodeFactory.WinVs.Loader.IVsLibraryConfiguration.ErrorDetails
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: CodeFactory.WinVs.Loader.IVsLibraryConfiguration.AssemblyFilePath*
  commentId: Overload:CodeFactory.WinVs.Loader.IVsLibraryConfiguration.AssemblyFilePath
  isExternal: true
  href: CodeFactory.WinVs.Loader.IVsLibraryConfiguration.html#CodeFactory_WinVs_Loader_IVsLibraryConfiguration_AssemblyFilePath
  name: AssemblyFilePath
  nameWithType: IVsLibraryConfiguration.AssemblyFilePath
  fullName: CodeFactory.WinVs.Loader.IVsLibraryConfiguration.AssemblyFilePath
- uid: CodeFactory.WinVs.Loader.IVsLibraryConfiguration.AssemblyStrongName*
  commentId: Overload:CodeFactory.WinVs.Loader.IVsLibraryConfiguration.AssemblyStrongName
  isExternal: true
  href: CodeFactory.WinVs.Loader.IVsLibraryConfiguration.html#CodeFactory_WinVs_Loader_IVsLibraryConfiguration_AssemblyStrongName
  name: AssemblyStrongName
  nameWithType: IVsLibraryConfiguration.AssemblyStrongName
  fullName: CodeFactory.WinVs.Loader.IVsLibraryConfiguration.AssemblyStrongName
- uid: CodeFactory.WinVs.Loader.IVsLibraryConfiguration.HasDebugInformation*
  commentId: Overload:CodeFactory.WinVs.Loader.IVsLibraryConfiguration.HasDebugInformation
  isExternal: true
  href: CodeFactory.WinVs.Loader.IVsLibraryConfiguration.html#CodeFactory_WinVs_Loader_IVsLibraryConfiguration_HasDebugInformation
  name: HasDebugInformation
  nameWithType: IVsLibraryConfiguration.HasDebugInformation
  fullName: CodeFactory.WinVs.Loader.IVsLibraryConfiguration.HasDebugInformation
