### YamlMime:ManagedReference
items:
- uid: CodeFactory.WinVs.IVsEnvironmentActions
  commentId: T:CodeFactory.WinVs.IVsEnvironmentActions
  id: IVsEnvironmentActions
  parent: CodeFactory.WinVs
  children:
  - CodeFactory.WinVs.IVsEnvironmentActions.WriteToCodeFactoryOutputWindowAsync(System.String)
  langs:
  - csharp
  - vb
  name: IVsEnvironmentActions
  nameWithType: IVsEnvironmentActions
  fullName: CodeFactory.WinVs.IVsEnvironmentActions
  type: Interface
  source:
    href: https://github.com/CodeFactoryLLC/CodeFactoryForWindows/blob/e63c05962945f61f2329e19d324f24a768806f18/Src/CodeFactoryForWindows/CodeFactory.WinVs/IVsEnvironmentActions.cs
  assemblies:
  - CodeFactory.WinVs
  namespace: CodeFactory.WinVs
  summary: Visual Studio actions handle interaction with Visual Studio itself.
  example: []
  syntax:
    content: public interface IVsEnvironmentActions
    content.vb: Public Interface IVsEnvironmentActions
- uid: CodeFactory.WinVs.IVsEnvironmentActions.WriteToCodeFactoryOutputWindowAsync(System.String)
  commentId: M:CodeFactory.WinVs.IVsEnvironmentActions.WriteToCodeFactoryOutputWindowAsync(System.String)
  id: WriteToCodeFactoryOutputWindowAsync(System.String)
  parent: CodeFactory.WinVs.IVsEnvironmentActions
  langs:
  - csharp
  - vb
  name: WriteToCodeFactoryOutputWindowAsync(string)
  nameWithType: IVsEnvironmentActions.WriteToCodeFactoryOutputWindowAsync(string)
  fullName: CodeFactory.WinVs.IVsEnvironmentActions.WriteToCodeFactoryOutputWindowAsync(string)
  type: Method
  source:
    href: https://github.com/CodeFactoryLLC/CodeFactoryForWindows/blob/e63c05962945f61f2329e19d324f24a768806f18/Src/CodeFactoryForWindows/CodeFactory.WinVs/IVsEnvironmentActions.cs
  assemblies:
  - CodeFactory.WinVs
  namespace: CodeFactory.WinVs
  summary: Writes the provided message to the CodeFactory output window in Visual Studio.
  example: []
  syntax:
    content: Task WriteToCodeFactoryOutputWindowAsync(string message)
    parameters:
    - id: message
      type: System.String
      description: The message to be written to the output window.
    return:
      type: System.Threading.Tasks.Task
    content.vb: Function WriteToCodeFactoryOutputWindowAsync(message As String) As Task
  overload: CodeFactory.WinVs.IVsEnvironmentActions.WriteToCodeFactoryOutputWindowAsync*
  nameWithType.vb: IVsEnvironmentActions.WriteToCodeFactoryOutputWindowAsync(String)
  fullName.vb: CodeFactory.WinVs.IVsEnvironmentActions.WriteToCodeFactoryOutputWindowAsync(String)
  name.vb: WriteToCodeFactoryOutputWindowAsync(String)
references:
- uid: CodeFactory.WinVs
  commentId: N:CodeFactory.WinVs
  isExternal: true
  href: CodeFactory.html
  name: CodeFactory.WinVs
  nameWithType: CodeFactory.WinVs
  fullName: CodeFactory.WinVs
  spec.csharp:
  - uid: CodeFactory
    name: CodeFactory
    isExternal: true
    href: CodeFactory.html
  - name: .
  - uid: CodeFactory.WinVs
    name: WinVs
    isExternal: true
    href: CodeFactory.WinVs.html
  spec.vb:
  - uid: CodeFactory
    name: CodeFactory
    isExternal: true
    href: CodeFactory.html
  - name: .
  - uid: CodeFactory.WinVs
    name: WinVs
    isExternal: true
    href: CodeFactory.WinVs.html
- uid: CodeFactory.WinVs.IVsEnvironmentActions.WriteToCodeFactoryOutputWindowAsync*
  commentId: Overload:CodeFactory.WinVs.IVsEnvironmentActions.WriteToCodeFactoryOutputWindowAsync
  isExternal: true
  href: CodeFactory.WinVs.IVsEnvironmentActions.html#CodeFactory_WinVs_IVsEnvironmentActions_WriteToCodeFactoryOutputWindowAsync_System_String_
  name: WriteToCodeFactoryOutputWindowAsync
  nameWithType: IVsEnvironmentActions.WriteToCodeFactoryOutputWindowAsync
  fullName: CodeFactory.WinVs.IVsEnvironmentActions.WriteToCodeFactoryOutputWindowAsync
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: System.Threading.Tasks.Task
  commentId: T:System.Threading.Tasks.Task
  parent: System.Threading.Tasks
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.threading.tasks.task
  name: Task
  nameWithType: Task
  fullName: System.Threading.Tasks.Task
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: System.Threading.Tasks
  commentId: N:System.Threading.Tasks
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System.Threading.Tasks
  nameWithType: System.Threading.Tasks
  fullName: System.Threading.Tasks
  spec.csharp:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Threading
    name: Threading
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading
  - name: .
  - uid: System.Threading.Tasks
    name: Tasks
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading.tasks
  spec.vb:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Threading
    name: Threading
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading
  - name: .
  - uid: System.Threading.Tasks
    name: Tasks
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading.tasks
