### YamlMime:ManagedReference
items:
- uid: CodeFactory.WinVs.Commands.IConfigGuidance
  commentId: T:CodeFactory.WinVs.Commands.IConfigGuidance
  id: IConfigGuidance
  parent: CodeFactory.WinVs.Commands
  children:
  - CodeFactory.WinVs.Commands.IConfigGuidance.Guidance
  langs:
  - csharp
  - vb
  name: IConfigGuidance
  nameWithType: IConfigGuidance
  fullName: CodeFactory.WinVs.Commands.IConfigGuidance
  type: Interface
  source:
    href: https://github.com/CodeFactoryLLC/CodeFactoryForWindows/blob/e63c05962945f61f2329e19d324f24a768806f18/Src/CodeFactoryForWindows/CodeFactory.WinVs/Commands/IConfigGuidance.cs
  assemblies:
  - CodeFactory.WinVs
  namespace: CodeFactory.WinVs.Commands
  summary: Contract definition for guidance for command configuration
  example: []
  syntax:
    content: public interface IConfigGuidance
    content.vb: Public Interface IConfigGuidance
- uid: CodeFactory.WinVs.Commands.IConfigGuidance.Guidance
  commentId: P:CodeFactory.WinVs.Commands.IConfigGuidance.Guidance
  id: Guidance
  parent: CodeFactory.WinVs.Commands.IConfigGuidance
  langs:
  - csharp
  - vb
  name: Guidance
  nameWithType: IConfigGuidance.Guidance
  fullName: CodeFactory.WinVs.Commands.IConfigGuidance.Guidance
  type: Property
  source:
    href: https://github.com/CodeFactoryLLC/CodeFactoryForWindows/blob/e63c05962945f61f2329e19d324f24a768806f18/Src/CodeFactoryForWindows/CodeFactory.WinVs/Commands/IConfigGuidance.cs
  assemblies:
  - CodeFactory.WinVs
  namespace: CodeFactory.WinVs.Commands
  summary: Instructions for what data is to go into the configuration.
  example: []
  syntax:
    content: string Guidance { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Property Guidance As String
  overload: CodeFactory.WinVs.Commands.IConfigGuidance.Guidance*
references:
- uid: CodeFactory.WinVs.Commands
  commentId: N:CodeFactory.WinVs.Commands
  isExternal: true
  href: CodeFactory.html
  name: CodeFactory.WinVs.Commands
  nameWithType: CodeFactory.WinVs.Commands
  fullName: CodeFactory.WinVs.Commands
  spec.csharp:
  - uid: CodeFactory
    name: CodeFactory
    isExternal: true
    href: CodeFactory.html
  - name: .
  - uid: CodeFactory.WinVs
    name: WinVs
    isExternal: true
    href: CodeFactory.WinVs.html
  - name: .
  - uid: CodeFactory.WinVs.Commands
    name: Commands
    isExternal: true
    href: CodeFactory.WinVs.Commands.html
  spec.vb:
  - uid: CodeFactory
    name: CodeFactory
    isExternal: true
    href: CodeFactory.html
  - name: .
  - uid: CodeFactory.WinVs
    name: WinVs
    isExternal: true
    href: CodeFactory.WinVs.html
  - name: .
  - uid: CodeFactory.WinVs.Commands
    name: Commands
    isExternal: true
    href: CodeFactory.WinVs.Commands.html
- uid: CodeFactory.WinVs.Commands.IConfigGuidance.Guidance*
  commentId: Overload:CodeFactory.WinVs.Commands.IConfigGuidance.Guidance
  isExternal: true
  href: CodeFactory.WinVs.Commands.IConfigGuidance.html#CodeFactory_WinVs_Commands_IConfigGuidance_Guidance
  name: Guidance
  nameWithType: IConfigGuidance.Guidance
  fullName: CodeFactory.WinVs.Commands.IConfigGuidance.Guidance
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
