### YamlMime:ManagedReference
items:
- uid: CodeFactory.WinVs.Loader.IVsActionConfiguration
  commentId: T:CodeFactory.WinVs.Loader.IVsActionConfiguration
  id: IVsActionConfiguration
  parent: CodeFactory.WinVs.Loader
  children:
  - CodeFactory.WinVs.Loader.IVsActionConfiguration.ActionAssemblyFullName
  - CodeFactory.WinVs.Loader.IVsActionConfiguration.Title
  - CodeFactory.WinVs.Loader.IVsActionConfiguration.VisualStudioActionType
  langs:
  - csharp
  - vb
  name: IVsActionConfiguration
  nameWithType: IVsActionConfiguration
  fullName: CodeFactory.WinVs.Loader.IVsActionConfiguration
  type: Interface
  source:
    href: https://github.com/CodeFactoryLLC/CodeFactoryForWindows/blob/e63c05962945f61f2329e19d324f24a768806f18/Src/CodeFactoryForWindows/CodeFactory.WinVs/Loader/IVsActionConfiguration.cs
  assemblies:
  - CodeFactory.WinVs
  namespace: CodeFactory.WinVs.Loader
  summary: Configuration data model that holds loading information for loading a target visual studio command into code factory.
  example: []
  syntax:
    content: public interface IVsActionConfiguration
    content.vb: Public Interface IVsActionConfiguration
- uid: CodeFactory.WinVs.Loader.IVsActionConfiguration.ActionAssemblyFullName
  commentId: P:CodeFactory.WinVs.Loader.IVsActionConfiguration.ActionAssemblyFullName
  id: ActionAssemblyFullName
  parent: CodeFactory.WinVs.Loader.IVsActionConfiguration
  langs:
  - csharp
  - vb
  name: ActionAssemblyFullName
  nameWithType: IVsActionConfiguration.ActionAssemblyFullName
  fullName: CodeFactory.WinVs.Loader.IVsActionConfiguration.ActionAssemblyFullName
  type: Property
  source:
    href: https://github.com/CodeFactoryLLC/CodeFactoryForWindows/blob/e63c05962945f61f2329e19d324f24a768806f18/Src/CodeFactoryForWindows/CodeFactory.WinVs/Loader/IVsActionConfiguration.cs
  assemblies:
  - CodeFactory.WinVs
  namespace: CodeFactory.WinVs.Loader
  summary: The assembly full name for an command.
  example: []
  syntax:
    content: string ActionAssemblyFullName { get; }
    parameters: []
    return:
      type: System.String
    content.vb: ReadOnly Property ActionAssemblyFullName As String
  overload: CodeFactory.WinVs.Loader.IVsActionConfiguration.ActionAssemblyFullName*
- uid: CodeFactory.WinVs.Loader.IVsActionConfiguration.Title
  commentId: P:CodeFactory.WinVs.Loader.IVsActionConfiguration.Title
  id: Title
  parent: CodeFactory.WinVs.Loader.IVsActionConfiguration
  langs:
  - csharp
  - vb
  name: Title
  nameWithType: IVsActionConfiguration.Title
  fullName: CodeFactory.WinVs.Loader.IVsActionConfiguration.Title
  type: Property
  source:
    href: https://github.com/CodeFactoryLLC/CodeFactoryForWindows/blob/e63c05962945f61f2329e19d324f24a768806f18/Src/CodeFactoryForWindows/CodeFactory.WinVs/Loader/IVsActionConfiguration.cs
  assemblies:
  - CodeFactory.WinVs
  namespace: CodeFactory.WinVs.Loader
  summary: The title that is assigned to the command.
  example: []
  syntax:
    content: string Title { get; }
    parameters: []
    return:
      type: System.String
    content.vb: ReadOnly Property Title As String
  overload: CodeFactory.WinVs.Loader.IVsActionConfiguration.Title*
- uid: CodeFactory.WinVs.Loader.IVsActionConfiguration.VisualStudioActionType
  commentId: P:CodeFactory.WinVs.Loader.IVsActionConfiguration.VisualStudioActionType
  id: VisualStudioActionType
  parent: CodeFactory.WinVs.Loader.IVsActionConfiguration
  langs:
  - csharp
  - vb
  name: VisualStudioActionType
  nameWithType: IVsActionConfiguration.VisualStudioActionType
  fullName: CodeFactory.WinVs.Loader.IVsActionConfiguration.VisualStudioActionType
  type: Property
  source:
    href: https://github.com/CodeFactoryLLC/CodeFactoryForWindows/blob/e63c05962945f61f2329e19d324f24a768806f18/Src/CodeFactoryForWindows/CodeFactory.WinVs/Loader/IVsActionConfiguration.cs
  assemblies:
  - CodeFactory.WinVs
  namespace: CodeFactory.WinVs.Loader
  summary: The type of visual studio command being loaded.
  example: []
  syntax:
    content: VsCommandType VisualStudioActionType { get; }
    parameters: []
    return:
      type: CodeFactory.WinVs.Commands.VsCommandType
    content.vb: ReadOnly Property VisualStudioActionType As VsCommandType
  overload: CodeFactory.WinVs.Loader.IVsActionConfiguration.VisualStudioActionType*
references:
- uid: CodeFactory.WinVs.Loader
  commentId: N:CodeFactory.WinVs.Loader
  isExternal: true
  href: CodeFactory.html
  name: CodeFactory.WinVs.Loader
  nameWithType: CodeFactory.WinVs.Loader
  fullName: CodeFactory.WinVs.Loader
  spec.csharp:
  - uid: CodeFactory
    name: CodeFactory
    isExternal: true
    href: CodeFactory.html
  - name: .
  - uid: CodeFactory.WinVs
    name: WinVs
    isExternal: true
    href: CodeFactory.WinVs.html
  - name: .
  - uid: CodeFactory.WinVs.Loader
    name: Loader
    isExternal: true
    href: CodeFactory.WinVs.Loader.html
  spec.vb:
  - uid: CodeFactory
    name: CodeFactory
    isExternal: true
    href: CodeFactory.html
  - name: .
  - uid: CodeFactory.WinVs
    name: WinVs
    isExternal: true
    href: CodeFactory.WinVs.html
  - name: .
  - uid: CodeFactory.WinVs.Loader
    name: Loader
    isExternal: true
    href: CodeFactory.WinVs.Loader.html
- uid: CodeFactory.WinVs.Loader.IVsActionConfiguration.ActionAssemblyFullName*
  commentId: Overload:CodeFactory.WinVs.Loader.IVsActionConfiguration.ActionAssemblyFullName
  isExternal: true
  href: CodeFactory.WinVs.Loader.IVsActionConfiguration.html#CodeFactory_WinVs_Loader_IVsActionConfiguration_ActionAssemblyFullName
  name: ActionAssemblyFullName
  nameWithType: IVsActionConfiguration.ActionAssemblyFullName
  fullName: CodeFactory.WinVs.Loader.IVsActionConfiguration.ActionAssemblyFullName
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: CodeFactory.WinVs.Loader.IVsActionConfiguration.Title*
  commentId: Overload:CodeFactory.WinVs.Loader.IVsActionConfiguration.Title
  isExternal: true
  href: CodeFactory.WinVs.Loader.IVsActionConfiguration.html#CodeFactory_WinVs_Loader_IVsActionConfiguration_Title
  name: Title
  nameWithType: IVsActionConfiguration.Title
  fullName: CodeFactory.WinVs.Loader.IVsActionConfiguration.Title
- uid: CodeFactory.WinVs.Loader.IVsActionConfiguration.VisualStudioActionType*
  commentId: Overload:CodeFactory.WinVs.Loader.IVsActionConfiguration.VisualStudioActionType
  isExternal: true
  href: CodeFactory.WinVs.Loader.IVsActionConfiguration.html#CodeFactory_WinVs_Loader_IVsActionConfiguration_VisualStudioActionType
  name: VisualStudioActionType
  nameWithType: IVsActionConfiguration.VisualStudioActionType
  fullName: CodeFactory.WinVs.Loader.IVsActionConfiguration.VisualStudioActionType
- uid: CodeFactory.WinVs.Commands.VsCommandType
  commentId: T:CodeFactory.WinVs.Commands.VsCommandType
  parent: CodeFactory.WinVs.Commands
  isExternal: true
  href: CodeFactory.WinVs.Commands.VsCommandType.html
  name: VsCommandType
  nameWithType: VsCommandType
  fullName: CodeFactory.WinVs.Commands.VsCommandType
- uid: CodeFactory.WinVs.Commands
  commentId: N:CodeFactory.WinVs.Commands
  isExternal: true
  href: CodeFactory.html
  name: CodeFactory.WinVs.Commands
  nameWithType: CodeFactory.WinVs.Commands
  fullName: CodeFactory.WinVs.Commands
  spec.csharp:
  - uid: CodeFactory
    name: CodeFactory
    isExternal: true
    href: CodeFactory.html
  - name: .
  - uid: CodeFactory.WinVs
    name: WinVs
    isExternal: true
    href: CodeFactory.WinVs.html
  - name: .
  - uid: CodeFactory.WinVs.Commands
    name: Commands
    isExternal: true
    href: CodeFactory.WinVs.Commands.html
  spec.vb:
  - uid: CodeFactory
    name: CodeFactory
    isExternal: true
    href: CodeFactory.html
  - name: .
  - uid: CodeFactory.WinVs
    name: WinVs
    isExternal: true
    href: CodeFactory.WinVs.html
  - name: .
  - uid: CodeFactory.WinVs.Commands
    name: Commands
    isExternal: true
    href: CodeFactory.WinVs.Commands.html
