### YamlMime:ManagedReference
items:
- uid: Serilog.Configuration
  commentId: N:Serilog.Configuration
  id: Serilog.Configuration
  children:
  - Serilog.Configuration.ILoggerSettings
  - Serilog.Configuration.LoggerAuditSinkConfiguration
  - Serilog.Configuration.LoggerDestructuringConfiguration
  - Serilog.Configuration.LoggerEnrichmentConfiguration
  - Serilog.Configuration.LoggerFilterConfiguration
  - Serilog.Configuration.LoggerMinimumLevelConfiguration
  - Serilog.Configuration.LoggerSettingsConfiguration
  - Serilog.Configuration.LoggerSinkConfiguration
  langs:
  - csharp
  - vb
  name: Serilog.Configuration
  nameWithType: Serilog.Configuration
  fullName: Serilog.Configuration
  type: Namespace
  assemblies:
  - Serilog
references:
- uid: Serilog.Configuration.ILoggerSettings
  commentId: T:Serilog.Configuration.ILoggerSettings
  parent: Serilog.Configuration
  isExternal: true
  href: Serilog.Configuration.ILoggerSettings.html
  name: ILoggerSettings
  nameWithType: ILoggerSettings
  fullName: Serilog.Configuration.ILoggerSettings
- uid: Serilog.Configuration.LoggerAuditSinkConfiguration
  commentId: T:Serilog.Configuration.LoggerAuditSinkConfiguration
  parent: Serilog.Configuration
  isExternal: true
  href: Serilog.Configuration.LoggerAuditSinkConfiguration.html
  name: LoggerAuditSinkConfiguration
  nameWithType: LoggerAuditSinkConfiguration
  fullName: Serilog.Configuration.LoggerAuditSinkConfiguration
- uid: Serilog.Configuration.LoggerDestructuringConfiguration
  commentId: T:Serilog.Configuration.LoggerDestructuringConfiguration
  parent: Serilog.Configuration
  isExternal: true
  href: Serilog.Configuration.LoggerDestructuringConfiguration.html
  name: LoggerDestructuringConfiguration
  nameWithType: LoggerDestructuringConfiguration
  fullName: Serilog.Configuration.LoggerDestructuringConfiguration
- uid: Serilog.Configuration.LoggerEnrichmentConfiguration
  commentId: T:Serilog.Configuration.LoggerEnrichmentConfiguration
  parent: Serilog.Configuration
  isExternal: true
  href: Serilog.Configuration.LoggerEnrichmentConfiguration.html
  name: LoggerEnrichmentConfiguration
  nameWithType: LoggerEnrichmentConfiguration
  fullName: Serilog.Configuration.LoggerEnrichmentConfiguration
- uid: Serilog.Configuration.LoggerFilterConfiguration
  commentId: T:Serilog.Configuration.LoggerFilterConfiguration
  parent: Serilog.Configuration
  isExternal: true
  href: Serilog.Configuration.LoggerFilterConfiguration.html
  name: LoggerFilterConfiguration
  nameWithType: LoggerFilterConfiguration
  fullName: Serilog.Configuration.LoggerFilterConfiguration
- uid: Serilog.Configuration.LoggerMinimumLevelConfiguration
  commentId: T:Serilog.Configuration.LoggerMinimumLevelConfiguration
  parent: Serilog.Configuration
  isExternal: true
  href: Serilog.Configuration.LoggerMinimumLevelConfiguration.html
  name: LoggerMinimumLevelConfiguration
  nameWithType: LoggerMinimumLevelConfiguration
  fullName: Serilog.Configuration.LoggerMinimumLevelConfiguration
- uid: Serilog.Configuration.LoggerSettingsConfiguration
  commentId: T:Serilog.Configuration.LoggerSettingsConfiguration
  parent: Serilog.Configuration
  isExternal: true
  href: Serilog.Configuration.LoggerSettingsConfiguration.html
  name: LoggerSettingsConfiguration
  nameWithType: LoggerSettingsConfiguration
  fullName: Serilog.Configuration.LoggerSettingsConfiguration
- uid: Serilog.Configuration.LoggerSinkConfiguration
  commentId: T:Serilog.Configuration.LoggerSinkConfiguration
  parent: Serilog.Configuration
  isExternal: true
  href: Serilog.Configuration.LoggerSinkConfiguration.html
  name: LoggerSinkConfiguration
  nameWithType: LoggerSinkConfiguration
  fullName: Serilog.Configuration.LoggerSinkConfiguration
- uid: Serilog.Configuration
  commentId: N:Serilog.Configuration
  isExternal: true
  href: Serilog.html
  name: Serilog.Configuration
  nameWithType: Serilog.Configuration
  fullName: Serilog.Configuration
  spec.csharp:
  - uid: Serilog
    name: Serilog
    isExternal: true
    href: Serilog.html
  - name: .
  - uid: Serilog.Configuration
    name: Configuration
    isExternal: true
    href: Serilog.Configuration.html
  spec.vb:
  - uid: Serilog
    name: Serilog
    isExternal: true
    href: Serilog.html
  - name: .
  - uid: Serilog.Configuration
    name: Configuration
    isExternal: true
    href: Serilog.Configuration.html
