### YamlMime:ManagedReference
items:
- uid: Serilog.Configuration.ILoggerSettings
  commentId: T:Serilog.Configuration.ILoggerSettings
  id: ILoggerSettings
  parent: Serilog.Configuration
  children:
  - Serilog.Configuration.ILoggerSettings.Configure(Serilog.LoggerConfiguration)
  langs:
  - csharp
  - vb
  name: ILoggerSettings
  nameWithType: ILoggerSettings
  fullName: Serilog.Configuration.ILoggerSettings
  type: Interface
  assemblies:
  - Serilog
  namespace: Serilog.Configuration
  summary: Implemented on types that apply settings to a logger configuration.
  example: []
  syntax:
    content: public interface ILoggerSettings
    content.vb: Public Interface ILoggerSettings
- uid: Serilog.Configuration.ILoggerSettings.Configure(Serilog.LoggerConfiguration)
  commentId: M:Serilog.Configuration.ILoggerSettings.Configure(Serilog.LoggerConfiguration)
  id: Configure(Serilog.LoggerConfiguration)
  parent: Serilog.Configuration.ILoggerSettings
  langs:
  - csharp
  - vb
  name: Configure(LoggerConfiguration)
  nameWithType: ILoggerSettings.Configure(LoggerConfiguration)
  fullName: Serilog.Configuration.ILoggerSettings.Configure(Serilog.LoggerConfiguration)
  type: Method
  assemblies:
  - Serilog
  namespace: Serilog.Configuration
  summary: Apply the settings to the logger configuration.
  example: []
  syntax:
    content: void Configure(LoggerConfiguration loggerConfiguration)
    parameters:
    - id: loggerConfiguration
      type: Serilog.LoggerConfiguration
      description: The logger configuration to apply settings to.
    content.vb: Sub Configure(loggerConfiguration As LoggerConfiguration)
  overload: Serilog.Configuration.ILoggerSettings.Configure*
references:
- uid: Serilog.Configuration
  commentId: N:Serilog.Configuration
  isExternal: true
  href: Serilog.html
  name: Serilog.Configuration
  nameWithType: Serilog.Configuration
  fullName: Serilog.Configuration
  spec.csharp:
  - uid: Serilog
    name: Serilog
    isExternal: true
    href: Serilog.html
  - name: .
  - uid: Serilog.Configuration
    name: Configuration
    isExternal: true
    href: Serilog.Configuration.html
  spec.vb:
  - uid: Serilog
    name: Serilog
    isExternal: true
    href: Serilog.html
  - name: .
  - uid: Serilog.Configuration
    name: Configuration
    isExternal: true
    href: Serilog.Configuration.html
- uid: Serilog.Configuration.ILoggerSettings.Configure*
  commentId: Overload:Serilog.Configuration.ILoggerSettings.Configure
  isExternal: true
  href: Serilog.Configuration.ILoggerSettings.html#Serilog_Configuration_ILoggerSettings_Configure_Serilog_LoggerConfiguration_
  name: Configure
  nameWithType: ILoggerSettings.Configure
  fullName: Serilog.Configuration.ILoggerSettings.Configure
- uid: Serilog.LoggerConfiguration
  commentId: T:Serilog.LoggerConfiguration
  parent: Serilog
  isExternal: true
  href: Serilog.LoggerConfiguration.html
  name: LoggerConfiguration
  nameWithType: LoggerConfiguration
  fullName: Serilog.LoggerConfiguration
- uid: Serilog
  commentId: N:Serilog
  isExternal: true
  href: Serilog.html
  name: Serilog
  nameWithType: Serilog
  fullName: Serilog
