### YamlMime:ManagedReference
items:
- uid: System.Runtime.CompilerServices.ConfiguredCancelableAsyncEnumerable`1.Enumerator
  commentId: T:System.Runtime.CompilerServices.ConfiguredCancelableAsyncEnumerable`1.Enumerator
  id: ConfiguredCancelableAsyncEnumerable`1.Enumerator
  parent: System.Runtime.CompilerServices
  children:
  - System.Runtime.CompilerServices.ConfiguredCancelableAsyncEnumerable`1.Enumerator.Current
  - System.Runtime.CompilerServices.ConfiguredCancelableAsyncEnumerable`1.Enumerator.DisposeAsync
  - System.Runtime.CompilerServices.ConfiguredCancelableAsyncEnumerable`1.Enumerator.MoveNextAsync
  langs:
  - csharp
  - vb
  name: ConfiguredCancelableAsyncEnumerable<T>.Enumerator
  nameWithType: ConfiguredCancelableAsyncEnumerable<T>.Enumerator
  fullName: System.Runtime.CompilerServices.ConfiguredCancelableAsyncEnumerable<T>.Enumerator
  type: Struct
  assemblies:
  - Microsoft.Bcl.AsyncInterfaces
  namespace: System.Runtime.CompilerServices
  summary: Provides an awaitable async enumerator that enables cancelable iteration and configured awaits.
  example: []
  syntax:
    content: public readonly struct ConfiguredCancelableAsyncEnumerable<T>.Enumerator
    content.vb: Public Structure ConfiguredCancelableAsyncEnumerable(Of T).Enumerator
  inheritedMembers:
  - System.ValueType.Equals(System.Object)
  - System.ValueType.GetHashCode
  - System.ValueType.ToString
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.GetType
  nameWithType.vb: ConfiguredCancelableAsyncEnumerable(Of T).Enumerator
  fullName.vb: System.Runtime.CompilerServices.ConfiguredCancelableAsyncEnumerable(Of T).Enumerator
  name.vb: ConfiguredCancelableAsyncEnumerable(Of T).Enumerator
- uid: System.Runtime.CompilerServices.ConfiguredCancelableAsyncEnumerable`1.Enumerator.MoveNextAsync
  commentId: M:System.Runtime.CompilerServices.ConfiguredCancelableAsyncEnumerable`1.Enumerator.MoveNextAsync
  id: MoveNextAsync
  parent: System.Runtime.CompilerServices.ConfiguredCancelableAsyncEnumerable`1.Enumerator
  langs:
  - csharp
  - vb
  name: MoveNextAsync()
  nameWithType: ConfiguredCancelableAsyncEnumerable<T>.Enumerator.MoveNextAsync()
  fullName: System.Runtime.CompilerServices.ConfiguredCancelableAsyncEnumerable<T>.Enumerator.MoveNextAsync()
  type: Method
  assemblies:
  - Microsoft.Bcl.AsyncInterfaces
  namespace: System.Runtime.CompilerServices
  summary: Advances the enumerator asynchronously to the next element of the collection.
  example: []
  syntax:
    content: public ConfiguredValueTaskAwaitable<bool> MoveNextAsync()
    return:
      type: System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable{System.Boolean}
      description: >-
        A <xref href="System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable%601" data-throw-if-not-resolved="false"></xref> that will complete with a result of <code>true</code>

        if the enumerator was successfully advanced to the next element, or <code>false</code> if the enumerator has

        passed the end of the collection.
    content.vb: Public Function MoveNextAsync() As ConfiguredValueTaskAwaitable(Of Boolean)
  overload: System.Runtime.CompilerServices.ConfiguredCancelableAsyncEnumerable`1.Enumerator.MoveNextAsync*
  nameWithType.vb: ConfiguredCancelableAsyncEnumerable(Of T).Enumerator.MoveNextAsync()
  fullName.vb: System.Runtime.CompilerServices.ConfiguredCancelableAsyncEnumerable(Of T).Enumerator.MoveNextAsync()
- uid: System.Runtime.CompilerServices.ConfiguredCancelableAsyncEnumerable`1.Enumerator.DisposeAsync
  commentId: M:System.Runtime.CompilerServices.ConfiguredCancelableAsyncEnumerable`1.Enumerator.DisposeAsync
  id: DisposeAsync
  parent: System.Runtime.CompilerServices.ConfiguredCancelableAsyncEnumerable`1.Enumerator
  langs:
  - csharp
  - vb
  name: DisposeAsync()
  nameWithType: ConfiguredCancelableAsyncEnumerable<T>.Enumerator.DisposeAsync()
  fullName: System.Runtime.CompilerServices.ConfiguredCancelableAsyncEnumerable<T>.Enumerator.DisposeAsync()
  type: Method
  assemblies:
  - Microsoft.Bcl.AsyncInterfaces
  namespace: System.Runtime.CompilerServices
  summary: >-
    Performs application-defined tasks associated with freeing, releasing, or

    resetting unmanaged resources asynchronously.
  example: []
  syntax:
    content: public ConfiguredValueTaskAwaitable DisposeAsync()
    return:
      type: System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable
    content.vb: Public Function DisposeAsync() As ConfiguredValueTaskAwaitable
  overload: System.Runtime.CompilerServices.ConfiguredCancelableAsyncEnumerable`1.Enumerator.DisposeAsync*
  nameWithType.vb: ConfiguredCancelableAsyncEnumerable(Of T).Enumerator.DisposeAsync()
  fullName.vb: System.Runtime.CompilerServices.ConfiguredCancelableAsyncEnumerable(Of T).Enumerator.DisposeAsync()
- uid: System.Runtime.CompilerServices.ConfiguredCancelableAsyncEnumerable`1.Enumerator.Current
  commentId: P:System.Runtime.CompilerServices.ConfiguredCancelableAsyncEnumerable`1.Enumerator.Current
  id: Current
  parent: System.Runtime.CompilerServices.ConfiguredCancelableAsyncEnumerable`1.Enumerator
  langs:
  - csharp
  - vb
  name: Current
  nameWithType: ConfiguredCancelableAsyncEnumerable<T>.Enumerator.Current
  fullName: System.Runtime.CompilerServices.ConfiguredCancelableAsyncEnumerable<T>.Enumerator.Current
  type: Property
  assemblies:
  - Microsoft.Bcl.AsyncInterfaces
  namespace: System.Runtime.CompilerServices
  summary: Gets the element in the collection at the current position of the enumerator.
  example: []
  syntax:
    content: public T Current { get; }
    parameters: []
    return:
      type: '{T}'
    content.vb: Public ReadOnly Property Current As T
  overload: System.Runtime.CompilerServices.ConfiguredCancelableAsyncEnumerable`1.Enumerator.Current*
  nameWithType.vb: ConfiguredCancelableAsyncEnumerable(Of T).Enumerator.Current
  fullName.vb: System.Runtime.CompilerServices.ConfiguredCancelableAsyncEnumerable(Of T).Enumerator.Current
references:
- uid: System.Runtime.CompilerServices
  commentId: N:System.Runtime.CompilerServices
  isExternal: true
  href: System.html
  name: System.Runtime.CompilerServices
  nameWithType: System.Runtime.CompilerServices
  fullName: System.Runtime.CompilerServices
  spec.csharp:
  - uid: System
    name: System
    isExternal: true
    href: System.html
  - name: .
  - uid: System.Runtime
    name: Runtime
    isExternal: true
    href: System.Runtime.html
  - name: .
  - uid: System.Runtime.CompilerServices
    name: CompilerServices
    isExternal: true
    href: System.Runtime.CompilerServices.html
  spec.vb:
  - uid: System
    name: System
    isExternal: true
    href: System.html
  - name: .
  - uid: System.Runtime
    name: Runtime
    isExternal: true
    href: System.Runtime.html
  - name: .
  - uid: System.Runtime.CompilerServices
    name: CompilerServices
    isExternal: true
    href: System.Runtime.CompilerServices.html
- uid: System.ValueType.Equals(System.Object)
  commentId: M:System.ValueType.Equals(System.Object)
  parent: System.ValueType
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.valuetype.equals
  name: Equals(object)
  nameWithType: ValueType.Equals(object)
  fullName: System.ValueType.Equals(object)
  nameWithType.vb: ValueType.Equals(Object)
  fullName.vb: System.ValueType.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.ValueType.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.equals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.ValueType.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.equals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.ValueType.GetHashCode
  commentId: M:System.ValueType.GetHashCode
  parent: System.ValueType
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.valuetype.gethashcode
  name: GetHashCode()
  nameWithType: ValueType.GetHashCode()
  fullName: System.ValueType.GetHashCode()
  spec.csharp:
  - uid: System.ValueType.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.ValueType.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.gethashcode
  - name: (
  - name: )
- uid: System.ValueType.ToString
  commentId: M:System.ValueType.ToString
  parent: System.ValueType
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.valuetype.tostring
  name: ToString()
  nameWithType: ValueType.ToString()
  fullName: System.ValueType.ToString()
  spec.csharp:
  - uid: System.ValueType.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.ValueType.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.tostring
  - name: (
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.ValueType
  commentId: T:System.ValueType
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.valuetype
  name: ValueType
  nameWithType: ValueType
  fullName: System.ValueType
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1
  commentId: T:System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.runtime.compilerservices.configuredvaluetaskawaitable-1
  name: ConfiguredValueTaskAwaitable<TResult>
  nameWithType: ConfiguredValueTaskAwaitable<TResult>
  fullName: System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable<TResult>
  nameWithType.vb: ConfiguredValueTaskAwaitable(Of TResult)
  fullName.vb: System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable(Of TResult)
  name.vb: ConfiguredValueTaskAwaitable(Of TResult)
  spec.csharp:
  - uid: System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1
    name: ConfiguredValueTaskAwaitable
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.runtime.compilerservices.configuredvaluetaskawaitable-1
  - name: <
  - name: TResult
  - name: '>'
  spec.vb:
  - uid: System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1
    name: ConfiguredValueTaskAwaitable
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.runtime.compilerservices.configuredvaluetaskawaitable-1
  - name: (
  - name: Of
  - name: " "
  - name: TResult
  - name: )
- uid: System.Runtime.CompilerServices.ConfiguredCancelableAsyncEnumerable`1.Enumerator.MoveNextAsync*
  commentId: Overload:System.Runtime.CompilerServices.ConfiguredCancelableAsyncEnumerable`1.Enumerator.MoveNextAsync
  isExternal: true
  href: System.Runtime.CompilerServices.ConfiguredCancelableAsyncEnumerable-1.Enumerator.html#System_Runtime_CompilerServices_ConfiguredCancelableAsyncEnumerable_1_Enumerator_MoveNextAsync
  name: MoveNextAsync
  nameWithType: ConfiguredCancelableAsyncEnumerable<T>.Enumerator.MoveNextAsync
  fullName: System.Runtime.CompilerServices.ConfiguredCancelableAsyncEnumerable<T>.Enumerator.MoveNextAsync
  nameWithType.vb: ConfiguredCancelableAsyncEnumerable(Of T).Enumerator.MoveNextAsync
  fullName.vb: System.Runtime.CompilerServices.ConfiguredCancelableAsyncEnumerable(Of T).Enumerator.MoveNextAsync
- uid: System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable{System.Boolean}
  commentId: T:System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable{System.Boolean}
  parent: System.Runtime.CompilerServices
  definition: System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1
  href: https://learn.microsoft.com/dotnet/api/system.runtime.compilerservices.configuredvaluetaskawaitable-1
  name: ConfiguredValueTaskAwaitable<bool>
  nameWithType: ConfiguredValueTaskAwaitable<bool>
  fullName: System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable<bool>
  nameWithType.vb: ConfiguredValueTaskAwaitable(Of Boolean)
  fullName.vb: System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable(Of Boolean)
  name.vb: ConfiguredValueTaskAwaitable(Of Boolean)
  spec.csharp:
  - uid: System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1
    name: ConfiguredValueTaskAwaitable
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.runtime.compilerservices.configuredvaluetaskawaitable-1
  - name: <
  - uid: System.Boolean
    name: bool
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.boolean
  - name: '>'
  spec.vb:
  - uid: System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1
    name: ConfiguredValueTaskAwaitable
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.runtime.compilerservices.configuredvaluetaskawaitable-1
  - name: (
  - name: Of
  - name: " "
  - uid: System.Boolean
    name: Boolean
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.boolean
  - name: )
- uid: System.Runtime.CompilerServices.ConfiguredCancelableAsyncEnumerable`1.Enumerator.DisposeAsync*
  commentId: Overload:System.Runtime.CompilerServices.ConfiguredCancelableAsyncEnumerable`1.Enumerator.DisposeAsync
  isExternal: true
  href: System.Runtime.CompilerServices.ConfiguredCancelableAsyncEnumerable-1.Enumerator.html#System_Runtime_CompilerServices_ConfiguredCancelableAsyncEnumerable_1_Enumerator_DisposeAsync
  name: DisposeAsync
  nameWithType: ConfiguredCancelableAsyncEnumerable<T>.Enumerator.DisposeAsync
  fullName: System.Runtime.CompilerServices.ConfiguredCancelableAsyncEnumerable<T>.Enumerator.DisposeAsync
  nameWithType.vb: ConfiguredCancelableAsyncEnumerable(Of T).Enumerator.DisposeAsync
  fullName.vb: System.Runtime.CompilerServices.ConfiguredCancelableAsyncEnumerable(Of T).Enumerator.DisposeAsync
- uid: System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable
  commentId: T:System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable
  parent: System.Runtime.CompilerServices
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.runtime.compilerservices.configuredvaluetaskawaitable
  name: ConfiguredValueTaskAwaitable
  nameWithType: ConfiguredValueTaskAwaitable
  fullName: System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable
- uid: System.Runtime.CompilerServices.ConfiguredCancelableAsyncEnumerable`1.Enumerator.Current*
  commentId: Overload:System.Runtime.CompilerServices.ConfiguredCancelableAsyncEnumerable`1.Enumerator.Current
  isExternal: true
  href: System.Runtime.CompilerServices.ConfiguredCancelableAsyncEnumerable-1.Enumerator.html#System_Runtime_CompilerServices_ConfiguredCancelableAsyncEnumerable_1_Enumerator_Current
  name: Current
  nameWithType: ConfiguredCancelableAsyncEnumerable<T>.Enumerator.Current
  fullName: System.Runtime.CompilerServices.ConfiguredCancelableAsyncEnumerable<T>.Enumerator.Current
  nameWithType.vb: ConfiguredCancelableAsyncEnumerable(Of T).Enumerator.Current
  fullName.vb: System.Runtime.CompilerServices.ConfiguredCancelableAsyncEnumerable(Of T).Enumerator.Current
- uid: '{T}'
  commentId: '!:T'
  definition: T
  name: T
  nameWithType: T
  fullName: T
- uid: T
  name: T
  nameWithType: T
  fullName: T
